### ISSUE TITLE
src/RNMessageParser not found 

### ISSUE THREAD

**Issue by arul-prasad** [HMS-Core/hms-react-native-plugin#1]
after installed from npm package: 

https://npm.runkit.com/react-native-hwpush

we are facing the issue: src/RNMessageParser not found

error: bundling failed: Error: Unable to resolve module `./src/RNMessageParser` from `D:\Mobile-App\appsella-mobileapp\node_modules\react-native-hwpush\index.js`: The module `./src/RNMessageParser` could not be found from `D:\Mobile-App\appsella-mobileapp\node_modules\react-native-hwpush\index.js`. Indeed, none of these files exist:

**Comment by aktug** [comment]
Hi @arul-prasad ;

**Comment by aktug** [comment]
Hi @arul-prasad ;
You have to update version to **4.0.4-300**, it`s been solved this issue at this version 👍

**Comment by arul-prasad** [comment]
Hi @aktug ,

how I have update your version to 4.0.4-300?  i am getting only 4.0.4 from npm ?

c:\rn-huawei>npm i react-native-hwpush

 c:\rn-huawei\node_modules\react-native-hwpush

09/07/2020  14:20    <DIR>          .
09/07/2020  14:20    <DIR>          ..
09/07/2020  14:20    <DIR>          android
09/07/2020  14:20    <DIR>          example
26/10/1985  13:45               885 index.js
26/10/1985  13:45             9.138 LICENCE
09/07/2020  14:20             1.776 package.json
26/10/1985  13:45             3.903 README.md
               4 File(s)         15.702 bytes
               4 Dir(s)  166.556.307.456 bytes free

src/RNMessageParser not found ...

**Comment by aktug** [comment]
@arul-prasad you should delete the package-lock file and reinstall that package
**npm i react-native-hwpush@4.0.4-300**

**Comment by arul-prasad** [comment]
> **npm i react-native-hwpush@4.0.4-300**

Thanks a lot @aktug  it worked.
