### ISSUE TITLE
App crashes when installed on iOS/non Huawei Android device

### ISSUE THREAD

**Issue by biancadragomir** [HMS-Core/hms-react-native-plugin#119]
Hi! We integrated react-native-hms-push in our React Native app. It runs with no problems on Huawei phones, but the app crashes right when it starts if we run it on an iPhone or on other Android devices. There's no error and no logs in metro.
These are the versions of our dependencies (those that are relevant):

```
"@hmscore/react-native-hms-push": "^5.1.1-301",
"@react-native-agconnect/appmessaging": "1.2.0",
"@react-native-agconnect/core": "^1.2.0",
"@react-native-agconnect/crash": "1.2.0",
"react": "16.13.1",
"react-i18next": "^11.8.5",
"react-native": "0.63.4",
```

If I remove the react-native-hms-push dependency (and of course, the code that depends on it), the app starts. Anyone else running into this?

**Comment by simona-iuliana** [comment]
Hei, I fix this only for ios builds adding this code in App.tsx:  
```
useEffect(() => {
    let HMS;

    if (Platform.OS !== 'ios') {
      console.log('Nu ios');
      HMS = require('@hmscore/react-native-hms-push');

      HMS.HmsPushInstanceId.getToken('')
        .then((result: any) => {
          console.log('getToken', result);
        })
        .catch((err: any) => {
          console.log('[getToken] Error/Exception: ' + JSON.stringify(err));
        });
    }
```

But android builds still crash :😔 😭

**Comment by biancadragomir** [comment]
Android still crashes. This workaround prevents the iOS version from crashing, so it's a start. There is a library that allows you to check if the device has HMS, but even with this condition the app still crashes on Android (non-Huawei).

**Comment by ozcanozgur** [comment]
Hi @biancadragomir, thank you for your interest in our Huawei Push React Native Plugin,

Could you share with us more information about crash. Android Version, Error and is HMS Core installed?

**Comment by biancadragomir** [comment]
We tested it on OnePlus 7 with Android 11, Pixel 3 with Android 10. There is no error in metro, the app opens and crashes instantly. What do you mean by HMS core being installed? We have 
```
"@hmscore/react-native-hms-push": "^5.1.1-301",
 "@react-native-agconnect/core": "^1.2.0",
```
and the app works on 2 (tested) Huawei phones (P30 PRO and P10 lite).

**Comment by ozcanozgur** [comment]
Hi @biancadragomir,

You should install AppGallery then you can download the HMS Core app to your phone. HMS Core app have to be installed to use Huawei Mobile Services.

[https://consumer.huawei.com/tr/mobileservices/appgallery/](url)

Thank you for your interest.

**Comment by biancadragomir** [comment]
Hi @ozcanozgur! Thanks for your response, but I do not want the library to be instantiated on Android devices that have google services capabilities. We only need the library on Huawei devices which no longer support Firebase Push notifications due to not having google services

**Comment by simona-iuliana** [comment]
hi, @ozcanozgur ! I run the app on an android device, without Huawei services, and in my logcat I see this errors " HMSSDK_HMSPackageManager: Failed to find HMS apk " abd " HMSSDK_AGCUtils: Get appId with AGConnectServicesConfig failed
<img width="925" alt="Screenshot 2021-05-31 at 11 57 52" src="https://user-images.githubusercontent.com/62808255/120168348-70535080-c207-11eb-8f90-9f5c56f8d40a.png">
 "

**Comment by biancadragomir** [comment]
@ozcanozgur I just downloaded Huawei mobile services app from Play Store on a Pixel 3 device. But then this app just keeps crashing, and our app still cannot be run. Also, it is not ok to need the HMS app on Android devices in order to run the app... on non-Huawei Android devices I just want the library to be ignore, just like @simona-iuliana pointed out above in the code snippet

**Comment by nolife08021** [comment]
@biancadragomir  did you have any solution? I'm facing the same issue. And you're right, we can't like ask our users to install HMS service on their non-Huawei Android phone.

**Comment by ozcanozgur** [comment]
Hi all, 

Huawei mobile services app in the play store is not the right application for our services. You should install HMS Core Application from AppGallery or you can search the HMS Core apk from the internet.

Thank you.

**Comment by biancadragomir** [comment]
@ozcanozgur but we cannot ask ALL Android users to install HMS Core apk... we want to release the app both to Play Store and AppGallery and right now we cannot run the project on Android due to this dependency. is there any way to fix this or should we keep 2 separate package.json files? This is not very practical, but it's the last resort

**Comment by ozcanozgur** [comment]
Hi @biancadragomir,

You can use Huawei Availability React Native Plugin to  HMS Core APK detection on android devices. If there is not, the plugin provides navigation to AppGallery for HMS Core installation.

https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/about-0000001137975023

**Comment by biancadragomir** [comment]
Hi @ozcanozgur we are using that already, but the issue is that simply adding the dependency to the project, without even importing the library anywhere or writing any code, the project crashes on android... please look at @simona-iuliana's screenshot from above to see the errors that we get. thanks!

**Comment by ozcanozgur** [comment]
Hi @biancadragomir,

Thank you for your clear explanation, we are working on it and trying to fix it in shortest time!

**Comment by nolife08021** [comment]
@ozcanozgur  @biancadragomir  where to import HMSAvailability? I check the doc from the link below , but it only show that how to use it.https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/client-dev-0000001138591439

**Comment by ozcanozgur** [comment]
Hi @nolife08021,

You can use it before you import the push kit. It is related with where you are getting the error.

**Comment by nolife08021** [comment]
> Hi @nolife08021,
> 
> You can use it before you import the push kit. It is related with where you are getting the error.
Do you have any sample ? so sorry i'm confusing with it.

**Comment by ozcanozgur** [comment]
Hi @nolife08021 ,

You can check our availability library demo project.

https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Library-V1/rn-sdk-download-0000001140104403-V1

Thank You.

**Comment by ozcanozgur** [comment]
Hi @all,

The new version of push kit plugin released. 

[https://www.npmjs.com/package/@hmscore/react-native-hms-push](url)
[https://github.com/HMS-Core/hms-react-native-plugin/tree/master/react-native-hms-push](url)

Thank You.

**Comment by liho00** [comment]
site kit also having this issue, pls reopen it
![image](https://user-images.githubusercontent.com/77238199/132842764-2c20cf05-4ac7-48c5-8993-361aee6b919f.png)
