### ISSUE TITLE
account example wrong import

### ISSUE THREAD

**Issue by megaacheyounes** [HMS-Core/hms-react-native-plugin#12]
Hi

In account plugin exmaple, in App.js  (hms-react-native-plugin/react-native-hms-account/example/App.js::line 20), RNHMSAccount should be imported from "@hmscore/react-native-hms-account" not "react-native-hms-account"

**Comment by aktug** [comment]
Hi @megaacheyounes 

You're right, thanks for your attention🎁
We'll publish a new version of **@hmscore/react-native-hms-account** , it'll be fixed , thanks a lot again 👍
