### ISSUE TITLE
HMS Push notifications

### ISSUE THREAD

**Issue by tomto1** [HMS-Core/hms-react-native-plugin#122]
I im using HMS Push Notification with react native ( react-native-hms-push 5.0.2-301). I tested it on Huawei Mate 10 lite and it is working fine. But when in production on P40 lite i can't get token. How to solve problem?

**Comment by ozcanozgur** [comment]
Hi @tomto1,

The problem cause is probably HMS Core version. Could you please try it with different version. If the problem is persist try to disable auto_init or please wait for new version of push plugin. Will be released on july.

Thank You.
