### ISSUE TITLE
How to receive the Notification with Hms token please help me Please ?

### ISSUE THREAD

**Issue by Krish143git** [HMS-Core/hms-react-native-plugin#127]
I am integrating Huawei push kit in my project.i am able to receive the HMS token thorugh this

huaweiService =  async() =>{
    console.log('huawei service has started')   
    let HMS = require('@hmscore/react-native-hms-push');
    const hmsToken = await HMS.HmsPushInstanceId.getToken('');
    if (hmsToken) {
      console.log("HMS TOKEN ", hmsToken.result);
      AsyncStorage.setItem('@hms_token', hmsToken.result);
      store.dispatch(storeHMS(hmsToken.result));
    } else {
      console.log("HMS ERROR",hmsToken)
    }   
  }

what i need to do further to Display the Notifications in mY Device
1) Chanel creation is neccessary or optional like fireBase
2)how to receive the Notification When i send a Notification from a App Gallery connect with HMS token
3)how to get the Notification when the app is in BackGround or quite State

**Comment by ozcanozgur** [comment]
Hi @Krish143git thank you for using Huawei Push Kit,

1 -) There is no need for channel creation.

2 -) You can use onRemoteMessageReceivedListener and you can see other listener examples in our demo project.

```
this.onRemoteMessageReceivedListener = HmsPushEvent.onRemoteMessageReceived(
      (result) => {
        const RNRemoteMessageObj = new RNRemoteMessage(result.msg);
        HmsLocalNotification.localNotification({
          [HmsLocalNotification.Attr.title]: "DataMessage Received",
          [HmsLocalNotification.Attr
            .message]: RNRemoteMessageObj.getDataOfMap(),
        });
        this.log("onRemoteMessageReceived", result);
      }
    );
```

3 -) You should add the code below to your index.js file to display background notifications.
```
HmsPushMessaging.setBackgroundMessageHandler((dataMessage) => {
  HmsLocalNotification.localNotification({
    [HmsLocalNotification.Attr.title]: "[Headless] DataMessage Received",
    [HmsLocalNotification.Attr.message]: new RNRemoteMessage(
      dataMessage
    ).getDataOfMap(),
  })
    .then((result) => {
      console.log("[Headless] DataMessage Received", result);
    })
    .catch((err) => {
      console.log(
        "[LocalNotification Default] Error/Exception: " + JSON.stringify(err)
      );
    });

  return Promise.resolve();
});

```

Also, You can investigate our demo project to find samples for your questions.

https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Library-V1/reactnative-plugin-0000001050155850-V1

**Comment by Krish143git** [comment]
Thank you for the reply even they i already refered the example and written this code but this events  are not firing when i send the Notification Message from AppGalley

but With out implementing the any code with Hms token i am able to receive the Notification When the app is in Foreground

* But with implementing any code

**Comment by Krish143git** [comment]
Thank you it is working fine
