### ISSUE TITLE
Android App rejected "Remediation for Implicit PendingIntent Vulnerability"

### ISSUE THREAD

**Issue by sapramit** [HMS-Core/hms-react-native-plugin#128]
**Description**
Android app update rejected as Google states that the app contains an Implicit PendingIntent issue which can cause security threats in the form of denial-of-service, private data theft, and privilege escalation

**Expected behavior**
Google Play should accept the app
Google suggest https://support.google.com/faqs/answer/10437428

**Current behavior**
App update rejected by Google saying "Your app update has been rejected for not adhering to Google Play Developer Program policies".

**Screenshots**
<img width="958" alt="Screen Shot 2021-06-23 at 12 59 51 PM" src="https://user-images.githubusercontent.com/27512779/123069787-30f1db80-d424-11eb-8633-dbe332519ec3.png">

**Logs**
The following code uses PendingIntent.
         PendingIntent pendingIntent = PendingIntent.getBroadcast(getActivity().getApplicationContext(),
               requestCode, intent, PendingIntent.FLAG_UPDATE_CURRENT);

**Environment**
 - Platform: React-Native
 - Lib: @hmscore/react-native-hms-location
 - Lib Version 5.0.0-301
 - OS Version  Android API 23 and above

**Comment by ukasiu** [comment]
We are also affected

**Comment by sapramit** [comment]
It said to add FLAG_IMMUTABLE flag. I tried applying this patch as well but
again the same result.

-
+ int pendingIntentFlags = PendingIntent.FLAG_CANCEL_CURRENT;
+ if(android.os.Build.VERSION.SDK_INT >= 23) {
+ pendingIntentFlags |= PendingIntent.FLAG_IMMUTABLE;
+ }
return new NotificationCompat.Builder(this, CHANNEL_ID)
.setContentTitle(prefs.getString(Constants.KEY_CONTENT_TITLE,
Constants.DEFAULT_CONTENT_TITLE))
.setContentText(prefs.getString(Constants.KEY_CONTENT_TEXT,
Constants.DEFAULT_CONTENT_TEXT))
.setContentIntent(PendingIntent.getActivity(this, 0, new Intent(this,
getMainActivityClass()),
- PendingIntent.FLAG_CANCEL_CURRENT))
+ pendingIntentFlags))

+ int pendingIntentFlags = PendingIntent.FLAG_UPDATE_CURRENT;
+ if(android.os.Build.VERSION.SDK_INT >= 23) {
+ pendingIntentFlags |= PendingIntent.FLAG_IMMUTABLE;
+ }
PendingIntent pendingIntent =
PendingIntent.getBroadcast(getActivity().getApplicationContext(),
- requestCode, intent, PendingIntent.FLAG_UPDATE_CURRENT);
+ requestCode, intent, pendingIntentFlags);

**Comment by ozcanozgur** [comment]
Hi all, thank you for interest in our Huawei Location React Native Plugin.

Please go to “node_modules\@hmscore\react-native-hms-location\android\src\main\java\com\huawei\hms\rn\location\backend\interfaces\HMSProvider.java” file and change pending intent declaration from buildPendingIntent method for a quick fix. 

If result is successful we will fix the problem in the next release.

<img width="1393" alt="location" src="https://user-images.githubusercontent.com/13644092/123231042-8095dd00-d4e0-11eb-8fad-e44d29fdb18e.png">

```
public PendingIntent buildPendingIntent(int requestCode, String action) {
    Intent intent = new Intent();
    intent.setPackage(ctx.getPackageName());
    intent.setAction(action);
    PendingIntent pendingIntent;
    if (android.os.Build.VERSION.SDK_INT >= 23) {
        pendingIntent = PendingIntent.getBroadcast(ctx, requestCode, intent, PendingIntent.FLAG_UPDATE_CURRENT);
    } else {
        pendingIntent = PendingIntent.getBroadcast(ctx, requestCode, intent, 0);
    }
    this.requests.put(requestCode, pendingIntent);
    return pendingIntent;
}

```

Thank you!

**Comment by sapramit** [comment]
Hi ozcanozgur,
If we see the error reported. It says we should use 
if (android.os.Build.VERSION.SDK_INT >= 23) {
 // Create a PendingIntent using FLAG_IMMUTABLE
} else {
  // Existing code that creates a PendingIntent
}

So an appropriate fix would have been 
  int pendingIntentFlags = PendingIntent.FLAG_UPDATE_CURRENT;
  if(android.os.Build.VERSION.SDK_INT >= 23) {
      pendingIntentFlags |= PendingIntent.FLAG_IMMUTABLE;
  }
PendingIntent pendingIntent;
pendingIntent = PendingIntent.getBroadcast(ctx, requestCode, intent, pendingIntentFlags);

**Comment by ozcanozgur** [comment]
Hi @sapramit,

Thank you for suggestion, we will fix it with FLAG_IMMUTABLE.

**Comment by nolife08021** [comment]
@ozcanozgur Hi, I'am facing same issue but is from @hmscore/react-native-hms-push. Where should i change?
<img width="907" alt="Screenshot 2022-02-25 at 5 49 32 PM" src="https://user-images.githubusercontent.com/49778835/155693673-0f544f32-fdf4-4755-993b-7fb87e8d8318.png">
