### ISSUE TITLE
BackgroundNotifications are not Working pls any one help me

### ISSUE THREAD

**Issue by Krish143git** [HMS-Core/hms-react-native-plugin#129]
i was implemented Huawei push notifications in React-native 

1) for foreground Notifications it is working fine
2)But for Background it is not working this is the code i written 
3)i have tested by keeping it in index.js and App.js but the below event is not firing

  //background or kill state
    HMS.HmsPushMessaging.setBackgroundMessageHandler((dataMessage) => {
      console.log('setBackgroundMessageHandler',dataMessage)
      HmsLocalNotification.localNotification({
        [HmsLocalNotification.Attr.title]: "[Headless] DataMessage Received",
        [HmsLocalNotification.Attr.message]: new RNRemoteMessage(
          dataMessage
        ).getDataOfMap(),
      })
        .then((result) => {
          console.log("[Headless] DataMessage Received", result);
        })
        .catch((err) => {
          console.log(
            "[LocalNotification Default] Error/Exception: " + JSON.stringify(err)
          );
        });
    
      return Promise.resolve();
    });

**Comment by ozcanozgur** [comment]
Hi @Krish143git,

Please add necessary permissions to AndroidManifest.xml file.

`    <uses-permission android:name="android.permission.WAKE_LOCK" />
`

"WAKE_LOCK" Permission is needed to use background message feature.
Also you can check our demo project for another permissions.

[https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Library-V1/reactnative-plugin-0000001050155850-V1](url)

Thank you!

**Comment by Krish143git** [comment]
Even through I placed This Permission it is not Working. Presently i am using Realme Narge 30 pro  Device(GMS+HMS).

**Comment by ozcanozgur** [comment]
Hi @Krish143git,

I think, the problem related with integration. Could you please try our [demo](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Library-V1/reactnative-plugin-0000001050155850-V1) and test the background message feature. 

If the problem persist could you please share your Android version and EMUI version of your phone?

Thank You.
