### ISSUE TITLE
Normal Push Notification Listners are not available in React-native

### ISSUE THREAD

**Issue by Krish143git** [HMS-Core/hms-react-native-plugin#130]
Is there any listners to listen the Normal  msg Notifications (Not the Data Messages) in React-native

**Comment by ozcanozgur** [comment]
Hi @Krish143git,

We have only one listener for normal msg notifications.

```
 this.onNotificationOpenedAppListener = HmsPushEvent.onNotificationOpenedApp(
      (result) => {
        console.log("onNotificationOpenedApp", result);
      }
    );
```

If user click the notification, we can reach notification information with that listener.

Thank You!
