### ISSUE TITLE
Notifications not receiving in Kill State (Data Message)

### ISSUE THREAD

**Issue by vaibhgupta09** [HMS-Core/hms-react-native-plugin#137]
Notifications are not receiving whenever the app is in the kill state. 
setBackgroundMessageHandler method is not working in kill state but works in background state.

HmsPushMessaging.setBackgroundMessageHandler((dataMessage) => {
  HmsLocalNotification.localNotification({
    [HmsLocalNotification.Attr.title]: "[Headless] DataMessage Received",
    [HmsLocalNotification.Attr.message]: new RNRemoteMessage(
      dataMessage
    ).getDataOfMap(),
  })
    .then((result) => {
      console.log("[Headless] DataMessage Received", result);
    })
    .catch((err) => {
      console.log(
        "[LocalNotification Default] Error/Exception: " + JSON.stringify(err)
      );
    });
  return Promise.resolve();
});

**Comment by ozcanozgur** [comment]
Hi @vaibhgupta09,

Please add necessary permissions to AndroidManifest.xml file.

<uses-permission android:name="android.permission.WAKE_LOCK" />

"WAKE_LOCK" Permission is needed to use background message feature.
Also you can check our demo project for another permissions.

[https://github.com/HMS-Core/hms-react-native-plugin/tree/master/react-native-hms-push](url)

Thank you!

**Comment by vaibhgupta09** [comment]
hi @ozcanozgur 
I have added all the permissions which has been mentioned in demo project. 
 still unable to receive notification in kill state but the setBackgroundMessageHandler is calling when app in background state only.

**Comment by ozcanozgur** [comment]
Hi @vaibhgupta09,

I think, the problem related with integration. Could you please try our demo and test the background message feature.

If the problem persist could you please share your Android version and EMUI version of your phone?

Thank You.

**Comment by kirantripathi** [comment]
Hi @ozcanozgur , I am also having the same issue , Notification works when app is in background but not when it is killed   , so I don't assume it is  integration issue as we use "setBackgroundMessageHandler" for both killed and background state. I am checking in non huawei device.
I also have added the permission : <uses-permission android:name="android.permission.WAKE_LOCK" /> in manifest. 
Is there anything that I am missing.
@vaibhgupta09  were you able to solve the issue?

**Comment by sumit-neosoft** [comment]
Facing the same Issue

**Comment by ozcanozgur** [comment]
Hi @all, 

It seems to you all using non-Huawei devices. Is there any error on native side when trying to get notification at killed state? 
Also, we need to know Android, EMUI and Push Kit version.

We are sorry for the issue and thank you all for reporting.

**Comment by kirantripathi** [comment]
Hi @ozcanozgur  
package : @hmscore/react-native-hms-push": "^5.3.0-301"
device Model:Redmi Note 8
MIUI version :11.0.2
android version :9
facing issue with this specification

**Comment by ozcanozgur** [comment]
Hi @kirantripathi,

Could you please share your app AndroidManifes.xml file? 

Thank you for details.

**Comment by kirantripathi** [comment]
Hi  @ozcanozgur  , I can do that. I have removed wake lock permission at this one because adding that also didn't  have any impact to me.

`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.x.x">

    <uses-permission android:name="android.permission.INTERNET" />

  <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
<uses-permission android:name="android.permission.CAMERA"/>
<uses-permission android:name="android.permission.USE_FINGERPRINT" />
<uses-permission android:name="android.permission.USE_BIOMETRIC" />
<uses-permission android:name="android.permission.BLUETOOTH"/>
<uses-permission android:name="android.permission.BLUETOOTH_ADMIN"/>
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
<uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION"/>
<uses-permission android:name="android.permission.FOREGROUND_SERVICE"/> 


    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:usesCleartextTraffic="true"  
      android:theme="@style/AppTheme"
      android:supportsRtl="true"
      >
     


     
<service android:name="com.kontakt.sdk.android.ble.service.ProximityService" android:exported="false"/>



  <service android:name="com.huawei.hms.rn.push.services.MessagingHeadlessService" />
        <service
            android:name="com.huawei.hms.rn.push.remote.HmsPushMessageService"
            android:exported="false">
            <intent-filter>
                <action android:name="com.huawei.push.action.MESSAGING_EVENT" />
            </intent-filter>
        </service>

     
        <activity
          android:name=".SplashActivity"
          android:theme="@style/SplashTheme"
          android:label="@string/app_name">
          <intent-filter>
              <action android:name="android.intent.action.MAIN" />
              <category android:name="android.intent.category.LAUNCHER" />
          </intent-filter>
        </activity>
     
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize"
        android:exported="true"
         android:screenOrientation="portrait"
      
        >
        
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />

    

  

  

   <meta-data  android:name="com.dieam.reactnativepushnotification.notification_foreground"
                    android:value="false"/>
        
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_color"
                    android:resource="@color/white"/> 

        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationActions" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
            </intent-filter>
        </receiver>

        <service
            android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
            android:exported="false" >
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>


        
          
        <receiver
            android:name="com.huawei.hms.rn.location.RNLocationBroadcastReceiver"
            android:exported="false"
            android:enabled="true">
        <intent-filter>
            <action android:name="${applicationId}.ACTION_HMS_LOCATION" />
            <action android:name="${applicationId}.ACTION_HMS_ACTIVITY_IDENTIFICATION" />
            <action android:name="${applicationId}.ACTION_HMS_ACTIVITY_CONVERSION" />
            <action android:name="${applicationId}.ACTION_HMS_GEOFENCE" />
        </intent-filter>
        </receiver>
        <service android:name="com.huawei.hms.rn.location.RNTaskService" />


    </application>

</manifest>
`

**Comment by kirantripathi** [comment]
@ozcanozgur  any update on this ?

**Comment by ozcanozgur** [comment]
Hi @kirantripathi,

We tested our plugin on non-huawei android devices and there are no problem for sending data message on killed state.
Maybe your problem related with other services. Please try to create a new project with only hms push plugin and test it out.

In addition, you need to add "WAKE_LOCK" permission otherwise you will get an error same with the photo which added below. 

<img width="692" alt="withoutWakePermissionLog" src="https://user-images.githubusercontent.com/13644092/131974143-84aed30f-e037-4bc8-a877-6d4c9e57e28f.png">

Thank you.

**Comment by FabrizioCaldarelli** [comment]
To receive push notifications from killed app, you have to define the message handler as soon as possibile.

So, the right place where put the message handler is the "index.js" file, at the root of project.

My index.js file is like this:


```js
import {
    HmsLocalNotification,
    HmsPushMessaging,
} from "@hmscore/react-native-hms-push";
import { AppRegistry } from "react-native";
import App from "./App";
import { name as appName } from "./app.json";

AppRegistry.registerComponent(appName, () => App);

HmsPushMessaging.setBackgroundMessageHandler((dataMessage) => {
    console.log("HMSPluginService.setBackgroundMessageHandler", dataMessage);

    let dataJson = null;
    if (dataMessage.data) {
        try {
            dataJson = JSON.parse(dataMessage.data);
        } catch (e) {
            console.log(e);
        }
    }
    if (dataJson) {
        HmsLocalNotification.localNotification({
            [HmsLocalNotification.Attr.title]: "My App",
            [HmsLocalNotification.Attr.message]: dataJson.message,
            additionalData: dataJson,
        });
    }

    return Promise.resolve();
});

```

In this way I receive push notifications from killed app.

Also remember to use the library last version (at the moment of this writing is `5.3.0-301`)

**Comment by FabrizioCaldarelli** [comment]
@aktug This solution is working only on Huawei devices (tested in cloud debugging) but it does not work for Android + HMS devices, because it needs to change `HmsPushMessageService.java` and `MessaggingHeadlessService.java` to startForegroundService instead startService.
