### ISSUE TITLE
react-native-hms-map not working with Vue Native

### ISSUE THREAD

**Issue by melvinchng** [HMS-Core/hms-react-native-plugin#14]
### Background

I have `react-native-maps` installed in my Vue Native App. Now, I would like to extend my app to Huawei Devices. I installed `react-native-hms-map` but it seems having some issues. 

### Installation steps

1. `npm install @hmscore/react-native-hms-map`

### Attemps

I attempted using two methods, but both methods were not working either. I have the screenshots of the errors attached. 

Method 1

```
<template>
    ...
          {{ renderMap() }}
    ...
</template>
<script>
import MapView, { GroundOverlay, MapTypes,TileOverlay } from "@hmscore/react-native-hms-map";
import React from "react"

...
export defaults {
  methods: {
    renderMap() {
      return (
        <MapView mapType={MapTypes.NONE}>
          <TileOverlay
            tileProvider={{url: 'https://a.tile.openstreetmap.org/{z}/{x}/{y}.png'}}
          />
        </MapView>
      )
    }
  }
}
 </script>
```

![capture_method_1](https://user-images.githubusercontent.com/7425125/96593874-94b78800-131c-11eb-9eac-be1902cec7c0.jpg)

Method 2

This method is also the method I use to integrate with `react-native-maps`.

```
<template>
    ....
    <MapView :mapType="mapType">
      <TileOverlay
        :tileProvider="{url: 'https://a.tile.openstreetmap.org/{z}/{x}/{y}.png'}"
      />
    </MapView>
    ....
<template/>

<script>
import MapView, { GroundOverlay, MapTypes,TileOverlay } from "@hmscore/react-native-hms-map";

export defaults {
  data() {
    return {
      mapType: MapTypes.NONE
    }
  }
}
</scripts>
```

![Capture_method_2](https://user-images.githubusercontent.com/7425125/96593887-9aad6900-131c-11eb-9ae6-cbefbefe9f49.JPG)

### Versions
```
"@hmscore/react-native-hms-location": "^5.0.0-301",
"@hmscore/react-native-hms-map": "5.0.1-300",
"react": "16.11.0",
"react-native": "0.62.2",
"vue-native-core": "^0.1.4",
"vue-native-helper": "^0.1.4",
"vue-native-scripts": "^0.1.4"
``` 

Any idea?

**Comment by utarit** [comment]
Hi, I created an app via `npx react-native init` and followed [these ](https://vue-native.io/docs/installation.html#Configuring-a-React-Native-project-for-Vue-Native)steps to trasform vue native.

**Comment by utarit** [comment]
Hi, I created an app via `npx react-native init` and followed [these ](https://vue-native.io/docs/installation.html#Configuring-a-React-Native-project-for-Vue-Native) steps to trasform vue native. 
1. I installed hms map from [npm](https://www.npmjs.com/package/@hmscore/react-native-hms-map)
2. I followed these steps to connect app gallery: 

> ### AppGallery Connect Integration
> 
> * Add maven repository address and AppGallery Connect service dependencies into 'android/build.gradle' file.
> 
> ```
> maven {url 'https://developer.huawei.com/repo/'}
> classpath 'com.huawei.agconnect:agcp:1.4.1.300'
> ```
> 
> * Add AppGallery Connect plugin into 'android/app/build.gradle' file.
> 
> ```groovy
> apply plugin: 'com.huawei.agconnect'
> ```
> 
> * Download 'agconnect-services.json' file and put it under 'android/app' folder.
> 
> * Put keystore file under 'android/app' folder. Add signing configuration into 'android/app/build.gradle' file.
> 
> ```groovy
> signingConfigs {
>         release {
>             storeFile file('<keystore>')
>             storePassword '<storePassword>'
>             keyAlias '<keyAlias>'
>             keyPassword '<keyPassword>'
>         }
> 
>         debug {
>             storeFile file('<keystore>')
>             storePassword '<storePassword>'
>             keyAlias '<keyAlias>'
>             keyPassword '<keyPassword>'
>         }
>     }
>     buildTypes {
>         debug {
>             signingConfig signingConfigs.debug
>         }
>         release {
>             signingConfig signingConfigs.release
>             minifyEnabled enableProguardInReleaseBuilds
>             proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
>         }
>     }
> `

I tried this code which is similar to your method 2 but not containing typos/bugs, and it works well.
```
<template>
  <View class="container">
    <MapView class="mymap" :mapType="mapType">
      <TileOverlay
        :tileProvider="{url: 'https://a.tile.openstreetmap.org/{z}/{x}/{y}.png'}"
      />
    </MapView>
  </View>
</template>

<style>
.container {
  background-color: white;
  align-items: center;
  justify-content: center;
  flex: 1;
}
.mymap {
  height: 400;
  width: 400;
}
</style>

<script>
import MapView, {Marker,MapTypes, TileOverlay} from "@hmscore/react-native-hms-map";
export default {
  components: {MapView, Marker, TileOverlay},
  data() {
    return {
      mapType: MapTypes.NORMAL
    }
  }
}
</script>
```
Your first method gives the same error even when i just put `<text>Hello</text>` and not import any hms-map component at all.

**Comment by melvinchng** [comment]
I missed out the first two bullet points for AppGallery Connect Integration. However, after adding first two bullet points from AppGallery Connect Integration section I had to remove [mauron85/react-native-background-geolocation](https://github.com/mauron85/react-native-background-geolocation) from my app in order to build successfully. 

I used the sample code you attached, and installed a compiled app on P40 from Huawei Cloud Debugging for testing. I am receiving a blank screen (attached below).
 
![Capture](https://user-images.githubusercontent.com/7425125/97003391-f28ede80-156d-11eb-9782-43d45b588846.JPG)

**Comment by utarit** [comment]
Hi, you have to do all bullet points to get map data from Huawei repo. (All huawei kits require these steps)

You need to create an app in App gallery with a same package name with your app and you have to download the agconnect.json file into android/app folder.

You need to sign your app and copy the sha256 value into the textfield in App gallery page.

**Comment by melvinchng** [comment]
Hi, the comments [above](https://github.com/HMS-Core/hms-react-native-plugin/issues/14#issuecomment-715310604) has all the bullet points setup correctly, including the `agconnect-services.json`. 

I tested my `agconnect-services.json` in a fresh React Native app that has matching package name; It works flawlessly. However, when I plug it in on my existing  Vue Native app, no map is shown/rendered. I have included a logcat for debugging. There is something that caught my eye: [Line 109-143] shows that it failed to load map and failed to get location.

[2020-10-26 18 42 17.log](https://github.com/HMS-Core/hms-react-native-plugin/files/5438345/2020-10-26.18.42.17.log)

Here is a list of my packages that I use in my Vue Native app. I wonder if there is any package that causes this issue to happen.

[package-json.txt](https://github.com/HMS-Core/hms-react-native-plugin/files/5438365/package-json.txt)

**Comment by utarit** [comment]
```
java.lang.NoSuchMethodException: d*g*c*g*a*b*d*g*t*C*a*s*o*d*r*[*l*s* *a*a*l*n*.*t*i*g*
	at d.g.c.e.h.b.a(Unknown Source:27)
	at d.g.c.e.h.b.a(Unknown Source:9)
	at d.g.c.g.a.b.a(Unknown Source:224)
	at d.g.c.g.a.b.f(Unknown Source:45)
	at d.g.c.g.a.i.e.a(Unknown Source:0)
	at d.g.c.g.a.b.a(Unknown Source:22)
	at d.g.c.i.m.f0.c(Unknown Source:5)
	at d.g.c.i.m.f0.b(Unknown Source:8)
	at d.g.c.i.m.f0.a(Unknown Source:15)
	at d.g.c.i.g$a.a(Unknown Source:64)
	at d.g.c.g.a.a.a(Unknown Source:44)
	at d.g.c.g.a.a.a(Unknown Source:5)
	at d.g.c.i.g.a(Unknown Source:22)
	at com.huawei.hms.rn.map.RNHMSMapView.<init>(Unknown Source:99)
	at com.huawei.hms.rn.map.RNHMSMapView$Manager.createViewInstance(Unknown Source:7)
	at com.huawei.hms.rn.map.RNHMSMapView$Manager.createViewInstance(Unknown Source:0)
	at com.facebook.react.uimanager.ViewManager.createViewInstance(Unknown Source:0)
	at com.facebook.react.uimanager.ViewManager.createView(Unknown Source:0)
	at com.facebook.react.uimanager.m.a(Unknown Source:34)
	at com.facebook.react.uimanager.u0$e.execute(Unknown Source:23)
```

It seems like you get this weird error in your log, which i have never seen. Could you send me your gradle files and the JS file that calls the map?

**Comment by melvinchng** [comment]
Here are the files. Please rename the file extension to `.gradle`.

[`build.gradle`](https://github.com/HMS-Core/hms-react-native-plugin/files/5444469/build.txt)
[app/build.gradle](https://github.com/HMS-Core/hms-react-native-plugin/files/5444482/build.txt)

Also attaching `settings.gradle`, just in case if you need it
[settings.txt](https://github.com/HMS-Core/hms-react-native-plugin/files/5444500/settings.txt)

**Comment by utarit** [comment]
Hi, could you try to
1. remove nb- part 

```
<template>
      <MapView
        :style="{height: 400, width: 400}"
      >
      </MapView>
</template>
```
or

2. Do not import hms-location in the component and try again and see if it works.

**Comment by melvinchng** [comment]
Hi, this is my observation from your suggestions. 

I started removing everything (commented out all the import) and leaving just the code below.

```
<template>
    <View>
      <Text>Hello</Text>
      <Text>Hello</Text>
      <Text>Hello</Text>
    </View>
</template>
```

There is no [weird error](https://github.com/HMS-Core/hms-react-native-plugin/issues/14#issuecomment-717019778) recorded in logcat. I then import the Map, then the weird error was recorded in logcat.

```
<template>
    <View>
      <Text>Hello</Text>
      <Text>Hello</Text>
      <Text>Hello</Text>
      <MapView
        :style="{ height: 400, width: 400}"
      >
      </MapView>
    </View>
</template>

<script>
import MapView, {Marker,MapTypes, TileOverlay} from "@hmscore/react-native-hms-map";

export default {
  components: {
    MapView
  }
} 
```

**Comment by melvinchng** [comment]
@aktug This issue is still unresolved.

**Comment by utarit** [comment]
@melvinchng can you send the proguard file?

**Comment by melvinchng** [comment]
Here you go.

[proguard-rules.txt](https://github.com/HMS-Core/hms-react-native-plugin/files/5522544/proguard-rules.txt)

**Comment by utarit** [comment]
Hi, can you add these configurations to your proguard file and run the app again

```
-ignorewarnings 

-keepattributes *Annotation* 
-keepattributes Exceptions 
-keepattributes InnerClasses 
-keepattributes Signature 

-keep class com.hianalytics.android.**{*;} 
-keep class com.huawei.updatesdk.**{*;} 
-keep class com.huawei.hms.**{*;}

-repackageclasses
```

**Comment by melvinchng** [comment]
Thanks! Got it to work after adding the missing configurations provided.
