### ISSUE TITLE
[react-native-hms-location] Missing typescript support

### ISSUE THREAD

**Issue by Kaskeeeee** [HMS-Core/hms-react-native-plugin#152]
**Description**
Missing index.d.ts

**Expected behavior**
imports working

**Current behavior**
ide can't find imports folder

**Comment by i01000101** [comment]
Hi @Kaskeeeee, we have released the version 6.8.0-300 of React Native HMS Location Plugin with TypeScript support.

You can download it from [NPM](https://www.npmjs.com/package/@hmscore/react-native-hms-location/v/6.8.0-300).

Thank you for your interest.
