### ISSUE TITLE
Wrong version name in Maps demo

### ISSUE THREAD

**Issue by megaacheyounes** [HMS-Core/hms-react-native-plugin#153]
in '/hms-react-native-maps/example/packge.json#dependencies', the version of "@hmscore/react-native-hms-maps" should be "5.2.0-302" not "5.2.0.302"

**Comment by SerdarCanDev** [comment]
Hi @megaacheyounes , thank you for your interest in our Huawei Map React Native Package. The issue is resolved in our latest release.
