### ISSUE TITLE
[getToken] Error/Exception: {"nativeStackAndroid":[],"userInfo":null,"message":"907135700: get scope error","code":"907122045"}

### ISSUE THREAD

**Issue by slsasa** [HMS-Core/hms-react-native-plugin#154]
有在华为开发者联盟中创建项目，
    HmsPushInstanceId.getToken('')
      .then((result) => {
        console.log('getToken', result)
      })
      .catch((err) => {
        console.log('[getToken] Error/Exception: ' + JSON.stringify(err))
      }) 
这是我的方法调用

**Comment by SerdarCanDev** [comment]
Hi @slsasa , please check this [official documentation](https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/commonerror-0000001059816656) for error code "907135700" and reopen the issue if error persists.
