### ISSUE TITLE
Update react dependency

### ISSUE THREAD

**Issue by peltax** [HMS-Core/hms-react-native-plugin#155]
Hello,
react dependency is hardcoded to 16.x in package.json. This prevents npm installation without "--legacy-peer-deps" flag if one is using newer react-native such as 0.64, that uses react 17.x. Please update all react-native npm packages to allow other react versions.

> npm i @hmscore/react-native-hms-availability
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR! 
> npm ERR! While resolving: project@1.0.0
> npm ERR! Found: react@17.0.1
> npm ERR! node_modules/react
> npm ERR!   react@"17.0.1" from the root project
> npm ERR! 
> npm ERR! Could not resolve dependency:
> npm ERR! peer react@"^16.6.0" from @hmscore/react-native-hms-availability@5.2.0-300
> npm ERR! node_modules/@hmscore/react-native-hms-availability
> npm ERR!   @hmscore/react-native-hms-availability@"*" from the root project
> npm ERR! 
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force, or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by hu-qi** [comment]
The same.

![image](https://user-images.githubusercontent.com/17986122/144006817-bd44e336-7df8-4ecc-8c8a-4c953aa346c0.png)

**Comment by tarouboy** [comment]
I am using node version 18.2.0 and same here. ( RN 0.66 )
Can't do npm install with "--legacy-peer-deps" flag.

Please change the react dependency.
