### ISSUE TITLE
Circular referencing during evaluation for project ':app'. [Causes problem with Notifee]

### ISSUE THREAD

**Issue by orbulant** [HMS-Core/hms-react-native-plugin#156]
**This happens only when i use Notifee with Huawei Messaging Service (@hmscore/react-native-hms-push)**.

### I get this error when i run ./gradlew clean or building my android app.

```
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
--W- The variant: prodDebug, Use the json file: C:\myProject\android\app\agconnect-services.json

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\myProject\node_modules\@notifee\react-native\android\build.gradle' line: 21

* What went wrong:
A problem occurred evaluating project ':notifee_react-native'.
> Circular referencing during evaluation for project ':app'.
```

### Some things to note:
1. If i remove agconnect-services.json (part of the @hmscore/react-native-hms-push), this error does not appear and i am successfully able to run .**/gradlew clean**.
2. Commenting line 21 of the build.gradle file (C:\myProject\node_modules\@notifee\react-native\android\build.gradle) poses no issue, and i am able to use the build and use the app as intended. However this is not a long term solution... of course... so thats why im here asking.

Any ideas? 

Any recommendation on what to change in my build.gradle files (_android/app_ and _android/_) that will help solve this issue?

**Comment by ozcanozgur** [comment]
Hi @All,

We have tried the notifee package with our push plugin but we could not reproduce this error in our environment setup. This error is may be related with java version. Newer React Native versions need Java 11 to build android part of React Native. 

As another option you can try to upgrade agcp version.

![image](https://user-images.githubusercontent.com/13644092/162421154-afe4edfe-45e5-4f64-92ff-4abf7337d910.png)

If issue persist please feel free to contact us, you can share a quick demo with the error. Thank you for your interest.

**Comment by ErtugrulBEKTIK** [comment]
Changing the **agconnect** version fixed the problem.
```
buildscript {
    ...
    dependencies {
        ...
        //classpath 'com.huawei.agconnect:agcp:1.4.1.300'
        classpath 'com.huawei.agconnect:agcp:1.8.1.300'
    }
}

```
