### ISSUE TITLE
How I can fit all marker on button press is there any action that can fit all marker 

### ISSUE THREAD

**Issue by dilawer** [HMS-Core/hms-react-native-plugin#157]
**Description**
I want to make sure all marker fit so that we can see all marker at once
**Expected behavior**
What you expected to happen？
I want to achive same thing that we use in react-native-maps `fitToElements`
**Current behavior**
What actually happened？

**Screenshots**
If applicable, add screenshots to help explain your issue

**Logs**
Post logs here or paste them to [Ghostbin](https://ghostbin.co) and insert the link here.

**Environment**
 - Platform:React native
 - Kit: @hmscore/react-native-hms-map

**Comment by shilohchis** [comment]
Hi, maybe `setBounds` methods can help with that, here the [docs api link](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-References/mapview-0000001051150160#section41121748114415)
