### ISSUE TITLE
Program type already present: com.huawei.hms.rn.push.BuildConfig

### ISSUE THREAD

**Issue by chhornponleu** [HMS-Core/hms-react-native-plugin#16]
After integrating  [Push Kit](https://developer.huawei.com/consumer/en/doc/HMS-Plugin-Guides-V1/configure-app-0000001053537946-V1), I got this error

**Building app from command line got this error both `react-native run-android` and `./gradlew assembleRelease`**

```
> Task :app:transformClassesWithMultidexlistForRelease FAILED
D8: Program type already present: com.huawei.hms.rn.push.BuildConfig

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithMultidexlistForRelease'.
> com.android.build.api.transform.TransformException: Error while generating the main dex list:
  Error while merging dex archives: 
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: com.huawei.hms.rn.push.BuildConfig
```

>***However, running the app from Android Studio has no problem***

**App Info**

- React native: 0.61.5

**Comment by aktug** [comment]
Hello @chhornponleu ,
This issue is not related to Push Kit.

**Comment by aktug** [comment]
Hello @chhornponleu ,
This issue is not related to Push Kit.

local.properties
```
org.gradle.jvmargs=-XX\:MaxHeapSize\=512m -Xmx512m
```

build.gradle
```
defaultConfig {
    multiDexEnabled true //<-- Add this line
}
```

**Comment by chhornponleu** [comment]
@aktug that is not the solution

Actually, I already have multidex enabled in the project
```
    defaultConfig {
        applicationId "..."
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 2
        versionName "3.1"
        multiDexEnabled true
        ...
    }
```

I managed to solved the issue, btw
By undo the 'manual link' I manage to build successfully
> I followed the provided document which `manual link` the project while in **RN 0.61.5** is `auto link`

This issue shall be mention in the [document](https://developer.huawei.com/consumer/en/doc/HMS-Plugin-Guides-V1/integraternmodule-0000001050157791-V1)

**Comment by aktug** [comment]
thank you, we've changed these documents, in the next days will be updated. 👍👍
