### ISSUE TITLE
[react-native-hms-map] Add support for custom marker component

### ISSUE THREAD

**Issue by peltax** [HMS-Core/hms-react-native-plugin#160]
**Description**
react-native-maps allows user to render custom component with dynamically generated content as marker. HMS map only supports text and hardcoded image. 

**Expected behavior**
Expected ability to draw customized marker in specified map coordinates

**Current behavior**
Huawei users cannot see necessary info on map next to polygons.

**Environment**
 - Platform: React-Native
 - Kit: Map
 - Kit Version 5.2.0-302
 - Android 10, Honor 20 lite
 - Node v14

**Comment by MuhammedAlkhudiryAqar** [comment]
yes, please.

**Comment by ozcanozgur** [comment]
Hi @all,

You are able to modify the marker view with image, unfortunately for now our plugin doesn't have draw or custom view feature.

[Customise Marker Component](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/drawmap-0000001050032242#section92034557610)

Thank you for your interest.
