### ISSUE TITLE
installin issue 

### ISSUE THREAD

**Issue by abdouamyr** [HMS-Core/hms-react-native-plugin#162]
I tried to install it and I get this error 

![image](https://user-images.githubusercontent.com/34169772/143031188-a8bc250c-da52-4786-a5d0-70aa467464d4.png)

**Comment by hu-qi** [comment]
Add '--legacy-peer-deps', like:

`npm i @hmscore/react-native-hms-iap --legacy-peer-deps`
.

**Comment by abdouamyr** [comment]
thanks
