### ISSUE TITLE
[react-native-hms-push] can't read notification content

### ISSUE THREAD

**Issue by anyamiletic** [HMS-Core/hms-react-native-plugin#164]
**Description**
We have successfully integrated HMS Core into our app, and enabled the Push Kit. We are able to use `HmsPushInstanceId.getToken` to fetch the device token, and through AppGallery Connect, send a notification to the device. However, upon clicking the notification from the NC, we are not able to read the notification parameters (none of our callbacks are getting triggered). These are the listeners we have set up:

```javascript
  /** Handle push notification when app is in quit state (closed) */
    HmsPushMessaging.getInitialNotification()
      .then(remoteMessage => {
        console.log('initial notification message received: ', remoteMessage)
        return handleNotification(remoteMessage)
      })
      .catch((err) => {
        log.error(() => ['Error during getInitialNotification', err])
      })

/** Handle push notification when app is in background */
    HmsPushEvent.onNotificationOpenedApp((remoteMessage) => {
      console.log('foreground message received: ', remoteMessage)
      handleNotification(remoteMessage)
    })
```

**Expected behavior**
We expect that one of these listeners will fire when the notification is clicked on

**Current behavior**
The app opens, but nothing is written out in the console

**Logs**
on app reload the `HmsPushMessaging.getInitialNotification` fires:
```javascript
initial notification message received:  {"result": {}, "resultCode": "0"}
```

**Environment**
 - Platform: React-Native
 - Kit:  Push
 - Kit Version 5.3.0-304
 - OS Version: Huawei nova 8i,  Android 10, EMUI 11.0.1
 - Android Studio version 2020.3.1
 - Platform version React Native 0.66.1
 - Node Version  v16.11.1
 - Your Location/Region Serbia

**Other**
We couldn't find an example in the docs about handling just notifications (not data notifications, or topics) so we are not sure if these are the right handlers to use. When the app is in the foreground, background or killed, it is always the same case - no logs in the console, the listeners are not getting triggered. We have added the following in our `AndroidManifest.xml`:

```xml
<uses-permission android:name="android.permission.WAKE_LOCK" />
...

  <application>
    ....
    <service
      android:name=".DemoHmsMessageService"
      android:exported="false">
      <intent-filter>
        <action android:name="com.huawei.push.action.MESSAGING_EVENT"/>
      </intent-filter>
    </service>
  </application>

  <queries>
    <intent>
      <action android:name="com.huawei.hms.core.aidlservice" />
    </intent>
  </queries>
```

**Comment by anyamiletic** [comment]
We realised that by specifying a Custom Intent URI Page, the callbacks will fire as expected. So there was no change in the front-end code, only that every notification sent had to have the custom URI. Apparently this is a known issue, but i will still leave this issue open seeing as this is still buggy behaviour.

**Comment by ozcanozgur** [comment]
Hi @anyamiletic ,

We have tested the notification listeners with [demo application.](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Library/reactnative-plugin-0000001050155850)
According to our recent tests, there are no buggy behaviour with version: 6.3.0.302. 

We recommend you to try the latest updated version of React Native Push Kit. You should be careful with that, the onNotificationOpenedApp listener is called from index.js when application at killed state. Otherwise the getInitialNotification method is not a listener. You can try to call this metod manually after notification received to get received notification informations.


```
AppRegistry.registerComponent(appName, () => App);

HmsPushEvent.onNotificationOpenedApp((result) => {
  console.log("onNotificationOpenedApp", result);
  ToastAndroid.show(JSON.stringify(result, "\n", 4), ToastAndroid.SHORT);
});
```

If the issue persist, contact us here. Thank you for your interest.

**Comment by itsmeshusha** [comment]
Hi, everyone! I'm also facing a similar problem. Testing on a real device - Huawei P40 lite (JNY-LX1, EMUI 12.0.0)
"@hmscore/react-native-hms-push": "^6.12.0-301",

`HmsPushEvent.onNotificationOpenedApp` fails when opening notification from tray
`HmsPushMessaging.getInitialNotification()` triggers but no push data in the response
`{ "result": {}, "resultCode": "0"}`
