### ISSUE TITLE
Implicit PendingIntent Vulnerability

### ISSUE THREAD

**Issue by nolife08021** [HMS-Core/hms-react-native-plugin#177]
Description
Similar with [this](https://github.com/HMS-Core/hms-react-native-plugin/issues/128) issue but different plugin.
version:     "@hmscore/react-native-hms-push": "^5.3.0-304"

Expected behavior
Google Play should accept the app

Current behavior
App update rejected by Google saying "Your app update has been rejected for not adhering to Google Play Developer Program policies".

![image](https://user-images.githubusercontent.com/49778835/156488890-8853703f-f046-41ea-8656-fb12ba62c54d.png)

**Comment by Xuejiao-Shi** [comment]
hi @nolife08021 , pls try to update Push SDK to 6.1.0.300 Version. [Version Change History](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/version-change-history-0000001050155836#section5309103212536).

**Comment by sentientmachin3** [comment]
@nolife08021 are you still having this issue after the update?

**Comment by sentientmachin3** [comment]
After digging around for a while I found the issues being located in method `localNotificationScheduleSetAlarm`. Apparently the intent is being set with flag `PendingIntent.FLAG_UPDATE_CURRENT` (134217728) only, when it should be set to `PendingIntent.FLAG_UPDATE_CURRENT | PendingIntent.FLAG_IMMUTABLE`, (134217728 |  67108864).

**Comment by melimion** [comment]
@sentientmachin3 we still have this issue with lastest xamarin bindings (version [6.3.0.300])

**Comment by sentientmachin3** [comment]
We managed to cut all the HMSCore code off of Google build, problem solved. And frankly speaking, it looks even better.
