### ISSUE TITLE
Your app is not compliant with Google Play Policies

### ISSUE THREAD

**Issue by PaperMonster** [HMS-Core/hms-react-native-plugin#178]
We received an email from Google Play that our app is not compliant with Google Play Policies due to Huawei Mobile Services SDK. See following screenshot:
![policy-violation](https://user-images.githubusercontent.com/10735822/158740657-5b3d7a7c-4daf-444d-aa09-1d081253d4a2.png)

package.json
```
"@hmscore/react-native-hms-push": "^6.1.0-300",
```

android/build.gradle
```
buildscript {
    ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31
        ndkVersion = "21.4.7075529"
    }
    repositories {
        google()
        mavenCentral()
        jcenter()
        maven { 
            url 'https://developer.huawei.com/repo/'
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.2.2'
        classpath 'com.google.gms:google-services:4.3.10'
        classpath 'com.huawei.agconnect:agcp:1.4.1.300'
    }
}

allprojects {
    repositories {
        mavenCentral()
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            // url "$rootDir/../node_modules/react-native/android"
            // Replace AAR from original RN with AAR from react-native-v8
            url("$rootDir/../node_modules/react-native-v8/dist")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        maven {
            // prebuilt libv8android.so
            url("$rootDir/../node_modules/v8-android-jit/dist")
        }
        google()
        jcenter()
        // Huawei SDK
        maven { url 'http://developer.huawei.com/repo/' }
    }
}
```

**Comment by Xuejiao-Shi** [comment]
Thank you for providing the information regarding this issue. We are very sorry that it brings you inconvinience and are now investigating the root cause of it.

Could you kindly help us with some information to locate this issue? 

1.pls leave your APPID, app name and package name.

2. whether configured the following metadata in your app？ 
```
<meta-data 
android:name="com.huawei.hms.client.channel.androidMarket" 
android:value="false" />
```

**Comment by PaperMonster** [comment]
@Xuejiao-Shi 
1. `102381117`, `ชอบช้อป - ShobShop` and `com.shobshop.shobshopapp`
2. No, and don't see any in merged manifest.

**Comment by sentientmachin3** [comment]
We use `5.3.0-304` and we dont have this issue.

**Comment by Xuejiao-Shi** [comment]
@PaperMonster @adderly Your request has been received. We are aware of this issue and are currently investigating. Your application experience won't be affected at this time and we will continue to update you on solutions. Thanks for your understanding and support.

**Comment by adderly** [comment]
@Xuejiao-Shi I guess, we should have an answer by now..

**Comment by adderly** [comment]
@Xuejiao-Shi Any updates on this?

**Comment by alexfov** [comment]
I had to remove huawei libs to publish in google play.

**Comment by stefan-tremend** [comment]
Any updates on this issue? because those 4 months are coming to an end and will have to remove the huawei libs from app

**Comment by Xuejiao-Shi** [comment]
@stefan-tremend If you integrate the Push Kit React Native plugin, upgrade the plugin to the [latest version](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/version-change-history-0000001050155836#section17945161363319) will solve this issue.

**Comment by stefan-tremend** [comment]
> 

I have this packages 
    "@hmscore/react-native-hms-analytics": "^6.3.2-300",
    "@hmscore/react-native-hms-availability": "^5.2.0-300",
    "@hmscore/react-native-hms-location": "^5.1.0-303",
    "@hmscore/react-native-hms-map": "^6.0.1-304"
which one, needs to be updated?

**Comment by Xuejiao-Shi** [comment]
@stefan-tremend You can refer to [this document](https://developer.huawei.com/consumer/en/doc/HMS-Plugin-Guides-V1/version-change-history-0000001050140226-V1) to check the current latest versions of your integrated Kits and update them. For example, Currently the latest SDK version for hms-analytics is [6.3.2.301](https://developer.huawei.com/consumer/en/doc/HMS-Plugin-Guides-V1/version-change-history-0000001050159909-V1).

**Comment by skyplor** [comment]
@stefan-tremend you have to update your map kit to 6.3.1-304. They have stated that they `Deleted the capability of prompting users to install HMS Core (APK).` in that version

**Comment by PaperMonster** [comment]
With the latest  `@hmscore/react-native-hms-push` and `com.huawei.agconnect:agcp:1.4.2.301`, Google Play does not complain anymore. I'm closing this.

package.json
```
"@hmscore/react-native-hms-push": "^6.3.0-304",
```

android/build.gradle
```
classpath 'com.huawei.agconnect:agcp:1.4.2.301'
```
