### ISSUE TITLE
[location] mistake in docs

### ISSUE THREAD

**Issue by megaacheyounes** [HMS-Core/hms-react-native-plugin#19]
in Readme file of react-native-hms-location:
the method: `removeLocationUpdates` is in `FusedLocationModule`    

```javascript
HMSLocation.LocationKit.Native.removeLocationUpdates(locactionUpdateId)
  .then(_ => console.log("Remove location update successful"));
```
becoms:

```javascript
HMSLocation.FusedLocation.Native.removeLocationUpdates(locactionUpdateId)
  .then(_ => console.log("Remove location update successful"));
```

**Comment by megaacheyounes** [comment]
I see that `Event.removeFusedLocationEventListener does the same thing, which one is recommended for use?:
 
```javascript
HMSLocation.FusedLocation.Events.removeFusedLocationEventListener(locationUpdateId)
                .then(_ => console.log("*location remove update successful"));
```

**Comment by mustafahaluk** [comment]
`Event.removeFusedLocationEventListener` should be used to remove event listener added with `Event.addFusedLocationEventListener` function. 
On the other hand you can manually remove location updates(registered with `Native.requestLocationUpdatesWithCallback` or `Native.requestLocationUpdatesWithCallbackEx` functions) with `Native.removeLocationUpdates` function

**Comment by mustafahaluk** [comment]
> in Readme file of react-native-hms-location:
> the method: `removeLocationUpdates` is in `FusedLocationModule`
> 
> ```js
> HMSLocation.LocationKit.Native.removeLocationUpdates(locactionUpdateId)
>   .then(_ => console.log("Remove location update successful"));
> ```
> 
> becoms:
> 
> ```js
> HMSLocation.FusedLocation.Native.removeLocationUpdates(locactionUpdateId)
>   .then(_ => console.log("Remove location update successful"));
> ```

Yes we should change Readme like this. Thanks for the suggestion
