### ISSUE TITLE
Question: Which one should be used react-native-hms-push or react-native-hms-push-fcm

### ISSUE THREAD

**Issue by dilarakirn** [HMS-Core/hms-react-native-plugin#198]
Hi, i have a react native application which already uses firebase cloud messaging and i want to implement huawei push notification for devices that does not support google play services. There are two different packages which are react-native-hms-push or react-native-hms-push-fcm. Which one should be used ? The application should support both firebase cloud messaging and huawei push kit. 

Thanks

**Comment by Xuejiao-Shi** [comment]
In your case, react-native-hms-push should be used.
The react-native-hms-push-fcm plugin is used to receive messages on non-Huawei phones. If other plugins have been used, you do not need to use them.
https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/aggr-third-parties-0000001238262405

**Comment by dilarakirn** [comment]
Thank you for response, i will close the issue
