### ISSUE TITLE
@hmscore/react-native-hms-push installing only FCM

### ISSUE THREAD

**Issue by Foskas** [HMS-Core/hms-react-native-plugin#204]
Hi,

While installing @hmscore/react-native-hms-push on my React Native App, it's only added to the node_modules the react-native-hms-push-fcm and than the building proccess fails with the following error.

![Screenshot 2022-06-08 at 10 36 06](https://user-images.githubusercontent.com/39563017/172584670-d762fa01-d0c1-4001-bbe2-8f12e4a43fb2.png)

I'm not understanding how can I have the push kit installed correctly so I can use it on my Android React Native App. I followed all the steps from the official docs but there's something wrong with the instalation.

**Comment by Foskas** [comment]
> Have you configured these 2 lines in android/settings.gradle file? include ':react-native-hms-push' project(':react-native-hms-push').projectDir = new File(rootProject.projectDir, '../node_modules/@hmscore/react-native-hms-push/android')

Hi cooleizhu,

I did but the problem is I git installed on my node_modules the "react-native-hms-push-fcm" instead of "/eact-native-hms-push"

I did the install with yarn instead of npm, can that be the problem ?

**Comment by coolleizhu** [comment]
If you just need to use fcm, you just need to follow the configuration in this guide.
