### ISSUE TITLE
Question: How can I use Marker Image

### ISSUE THREAD

**Issue by chhornponleu** [HMS-Core/hms-react-native-plugin#21]
How can I use icon from

- URL ?
- local resource using `require('../images/pin.png')`

I have tried these without any luck
```
<Marker
    ...
    icon={{
        path: 'https://example.com/mypin.png',
    }}
```
```
<Marker
    ...
    icon={{
        path: require('../mypin.png'),
    }}
```

Reference Document
https://github.com/HMS-Core/hms-react-native-plugin/blob/master/react-native-hms-map/README.md#bitmapdescriptor

**Comment by utarit** [comment]
Hi, 
`path:` is for images that are in your android storage. Your app runs on your android device not on the PC so it doesn't recognize your development environement's resources.
Examples:
```
icon={{ path: "/sdcard/Download/icon.png",  }}

icon={{ path: "/storage/emulated/0/Download/icon.png",  }}
```

The best way to use custom images is that you add them in your android/app/src/main/assets folder.
![image](https://user-images.githubusercontent.com/19698300/97847300-767c5f80-1d00-11eb-9ecc-6fd9269ac795.png)

You can call them via `icon={{ asset: "ic_launcher.png", }}  // under assets folder`.

Also, downloading images from the internet is not supported in native SDK right now.

**Comment by chhornponleu** [comment]
Thanks for your response.
How about rendering `Component` as icon?

**Comment by utarit** [comment]
If you are asking doing this:
```
<Marker>
   <CustomIconView />
</Marker>
```
Unfortunately, it's not possible for now. Marker gets only InfoWindow as a child.

**Comment by chhornponleu** [comment]
Got it!
I can't wait to see this new feature soon!
