### ISSUE TITLE
Can you please help us to test our application in Huawei smartphones?

### ISSUE THREAD

**Issue by kfssoftware** [HMS-Core/hms-react-native-plugin#210]
We have an issue that we face in cloud debugging but not in real Huawei smartphones. However, we don't have a Huawei phone with Huawei software that we can test. Therefore, we kindly ask you to test our application on real Huawei smartphones.

The issue is that the map is not loading correctly. Please check and make sure that the map is loading correctly on all locations.

APK:
http://sendanywhe.re/4XK2L9N9

User info:
Username: test_huawei
Password: 123123

**Comment by Xuejiao-Shi** [comment]
It seems that your APK is not in the attachment. Can you send it to hmscore@huawei.com? I can test it for you.

**Comment by kfssoftware** [comment]
apk file; It is available at the link I mentioned in the description. Link: http://sendanywhe.re/4XK2L9N9

**Comment by kfssoftware** [comment]
Thanks a lot for your support. Can a few more people test it?

**Comment by coolleizhu** [comment]
Hello, I tried your app too.

You can find the video in your mail.
