### ISSUE TITLE
react-native-hms-availability 404 Not Found 

### ISSUE THREAD

**Issue by ahyong87** [HMS-Core/hms-react-native-plugin#211]
**Description**
receive email about not compliant with Google Play Policies due to Huawei Mobile Services SDK
so try upgrade @hmscore/react-native-hms-availability 5.2.0-300 to 6.4.0-303

**Expected behavior**
success upgrade to 6.4.0-303 

**Current behavior**
error An unexpected error occurred: "https://registry.yarnpkg.com/@hmscore/react-native-hms-availability/-/react-native-hms-availability-6.4.0-303.tgz: Request failed \"404 Not Found\"".
<img width="872" alt="Screenshot 2022-07-15 at 1 56 52 PM" src="https://user-images.githubusercontent.com/758214/179160256-5db6d723-b967-4418-bf1f-1a906eb87901.png">

**Comment by Xuejiao-Shi** [comment]
The related version has been released. You are advised to install it using npm:
https://www.npmjs.com/package/@hmscore/react-native-hms-availability

**Comment by ahyong87** [comment]
<img width="976" alt="Screenshot 2022-07-15 at 2 26 24 PM" src="https://user-images.githubusercontent.com/758214/179164334-935f31c9-ba0f-4d4c-ac40-bc9034287c2f.png">

i try 
npm i @hmscore/react-native-hms-availability
npm update @hmscore/react-native-hms-availability
yarn add @hmscore/react-native-hms-availability
yarn upgrade @hmscore/react-native-hms-availability 


still 404 in 6.4.0-303

**Comment by Xuejiao-Shi** [comment]
hi@[ahyong87](https://github.com/ahyong87) Please try upgrade to  `6.4.0-304` version.

**Comment by ahyong87** [comment]
Hi @Xuejiao-Shi working fine now. thank
