### ISSUE TITLE
@hmscore/react-native-hms-scan installation error

### ISSUE THREAD

**Issue by Kprashanth20** [HMS-Core/hms-react-native-plugin#212]
Description
While adding the library to the repo, facing the error 
<img width="744" alt="Screenshot 2022-07-18 at 7 38 32 PM" src="https://user-images.githubusercontent.com/82794989/179529943-c5f8fbb9-3b5d-49f7-91e9-75742f73f45f.png">

the solution I found is: to comment out the line 
in node_modules => @hmscore/react-native-hms-scan => android => build.gradle => apply plugin: 'maven'

<img width="318" alt="Screenshot 2022-07-18 at 7 40 42 PM" src="https://user-images.githubusercontent.com/82794989/179530359-da8daa2b-5826-46f8-a73d-3ac16febf081.png">

can this issue be fixed?

**Comment by Xuejiao-Shi** [comment]
You can try changing `apply plugin: 'maven'` to `apply plugin:'maven-publish'`.
