### ISSUE TITLE
Typescript support for @hmscore/react-native-hms-push 

### ISSUE THREAD

**Issue by whalemare** [HMS-Core/hms-react-native-plugin#213]
**Description**
Adding typescript support for library @hmscore/react-native-hms-push

**Expected behavior**
Reach developer experience with your library

**Current behavior**
Library not contains any types, only raw js files

**Screenshots**
No applicable

**Logs**
No applicable

**Environment**
No applicable

**Other**
No applicable

**Comment by ozkulbeng** [comment]
Hello @whalemare 

TypeScript support has been added to React Native Push plugin with the version 6.7.0-300.
You can find it on [npm](https://www.npmjs.com/package/@hmscore/react-native-hms-push).

Thank you for your interest in our plugins.
