### ISSUE TITLE
@hmscore/react-native-hms-scan: Google play policy voilation

### ISSUE THREAD

**Issue by Kprashanth20** [HMS-Core/hms-react-native-plugin#214]
- react native app gets rejected because of hms SDK used . how could it be fixed?
 package version : https://www.npmjs.com/package/@hmscore/react-native-hms-scan/v/1.3.1-301
 classpath 'com.huawei.agconnect:agcp:1.5.2.300'

**Comment by Xuejiao-Shi** [comment]
hi@[Kprashanth20](https://github.com/Kprashanth20) Can you provide the download link of your app in Google Play for us to check?

**Comment by Kprashanth20** [comment]
@Xuejiao-Shi https://play.google.com/store/search?q=inciflo&c=apps

**Comment by Xuejiao-Shi** [comment]
After click the link you provided, we can see that there are many apps. Which one is your app?
![image](https://user-images.githubusercontent.com/99166105/180937684-e09df861-9b34-4cf3-ae99-9f8e4311c6f2.png)
Or you can also send your released apk on Google Play to _hmscore@huawei.com_ for us to check.

**Comment by Kprashanth20** [comment]
@Xuejiao-Shi https://play.google.com/store/apps/details?id=com.godamwale.inciflo&hl=en_US&gl=US 
app name is inciflo

**Comment by Xuejiao-Shi** [comment]
Thank you for your feedback, it seems like you have integrated analytics in your project, please upgrade them to the latest version:[react-native-hms-analytics 6.3.2-301](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/version-change-history-0000001050159909). See more info on [HMS Core SDK Version Updates](https://stackoverflow.com/a/72474416/13329100).

**Note**: Before submitting a release to Google, also need to check the apk in Testing Track on Google Play Console. Ensure that the APK on all channels are using of the latest HMS Core SDK version.

**Comment by Kprashanth20** [comment]
@Xuejiao-Shi no i am just using react-native-hms-scan, nothing else from hms-core

**Comment by Xuejiao-Shi** [comment]
@Kprashanth20 You can try to run the gradlew -q :app:dependencies > dependency-list.txt command in the android directory to see the dependency-list.

**Comment by Kprashanth20** [comment]
[dependency-list.txt](https://github.com/HMS-Core/hms-react-native-plugin/files/9187705/dependency-list.txt)
@Xuejiao-Shi please check

**Comment by Xuejiao-Shi** [comment]
What we checked was the 1.1.6 version apk of the link you provided. Can i confirm what version are you checking? Would you mind send the apk you are checking to _hmscore@huawei.com_?

**Comment by ozcanozgur** [comment]
Hi @Kprashanth20 ,

React Native Scan Plugin has been upgraded to the latest SDK version(2.7.0-302) in which this issue had been resolved. You can find it at [npm](https://www.npmjs.com/package/@hmscore/react-native-hms-scan).
