### ISSUE TITLE
compileSdkVersion is not specified. Please add it to build.gradle error while building

### ISSUE THREAD

**Issue by ycdaskin** [HMS-Core/hms-react-native-plugin#218]
I am trying to use react-native-hms-location package but when i try to build my app i am getting this error:

compileSdkVersion is not specified. Please add it to build.gradle

I am pretty sure compileSdkVersion is added to build.gradle

```

buildscript {
    ext {
        buildToolsVersion = "31.0.0"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31
        googlePlayServicesVersion = "17.0.0"

        if (System.properties['os.arch'] == "aarch64") {
            // For M1 Users we need to use the NDK 24 which added support for aarch64
            ndkVersion = "24.0.8215888"
        } else if (Os.isFamily(Os.FAMILY_WINDOWS)) {
            // For Android Users, we need to use NDK 23, otherwise the build will
            // fail due to paths longer than the OS limit
            ndkVersion = "23.1.7779620"
        } else {
            // Otherwise we default to the side-by-side NDK version from AGP.
            ndkVersion = "21.4.7075529"
        }
    }


```
RN version: 0.68.1
Package version: 6.4.0-300

**Comment by Xuejiao-Shi** [comment]
Please check whether the following configurations exist:
![image](https://user-images.githubusercontent.com/99166105/186302832-80d8eda1-d906-4772-933f-de3863db4558.png)

https://github.com/HMS-Core/hms-react-native-plugin/blob/master/react-native-hms-location/example/android/app/build.gradle

**Comment by ycdaskin** [comment]
These configurations already exists:

![image](https://user-images.githubusercontent.com/41010080/187611826-af8416f7-46dd-4ab1-939b-920c8e6555bb.png)

This is not about it. When i remove this package i can compile successfully. The problem is the package itself.

**Comment by ozcanozgur** [comment]
Hi @ycdaskin,

The `compileSdkVersion is not specified` error is related to `maven-publish` issue of React Native ( #222 ) and already solved with a patch release. Please try the newest version of [Huawei RN Location plugin (6.4.0-301)](https://www.npmjs.com/package/@hmscore/react-native-hms-location) and let us know if the error persists.
