### ISSUE TITLE
Wrong declaration in module

### ISSUE THREAD

**Issue by gregersn** [HMS-Core/hms-react-native-plugin#22]
The following line does not correctly declare the module.
https://github.com/HMS-Core/hms-react-native-plugin/blob/7d437d48d5d8f80a367a8eae5a6b831dc6dae0fd/react-native-hms-map/src/index.d.ts#L16

It should be: `declare module "@hmscore/react-native-hms-map" {`

**Comment by utarit** [comment]
It will be changed in the next release.
