### ISSUE TITLE
A problem occurred evaluating project ':hmscore_react-native-hms-analytics'

### ISSUE THREAD

**Issue by Daha62** [HMS-Core/hms-react-native-plugin#220]
After updating react-native to version 0.68.3. I faced with such issue when build android:

A problem occurred evaluating project ':hmscore_react-native-hms-analytics'.
> Plugin with id 'maven' not found.

When I try to create a patch with _apply plugin:'maven-publish'_, I got an issue with the work of hmsAnalytics package. 

"@hmscore/react-native-hms-analytics": "6.3.2-301"

**Comment by Xuejiao-Shi** [comment]
Please modify the build.gradle file in this directory : `maven` -> `maven-publish`. like following:

![image](https://user-images.githubusercontent.com/99166105/189090178-0ff49f69-742e-4def-8d17-d16beb0aeda1.png)

**Comment by ozkulbeng** [comment]
Hello @Daha62 
The 'maven' issue has been resolved with the latest version of the React Native HMS Analytics plugin. You can find it in [npm](https://www.npmjs.com/package/@hmscore/react-native-hms-analytics).
