### ISSUE TITLE
setBackgroundMessageHandler is not working

### ISSUE THREAD

**Issue by Daha62** [HMS-Core/hms-react-native-plugin#221]
Hi!
I'm trying to catch push-notifications in background or killed state of app, but **HmsPushMessaging.setBackgroundMessageHandler** not fired at all (I've done exactly the [same](https://developer.huawei.com/consumer/en/doc/HMS-Plugin-Guides/receivedatamsgkilled-0000001058551962-V1).)

Also I was trying to catch notification when app is in foreground with **HmsPushEvent.onRemoteMessageReceived** - it also doesnt work.

(in both cases push was delivered successfully)

I was trying to check another functions like:  **HmsPushEvent.onLocalNotificationAction**,  **HmsPushEvent.onPushMessageSentDelivered** they also aren't working.

It seemed that **com.huawei.hms.rn.push.remote.HmsPushMessageService** is not started.

Any ideas? 

"react-native": "0.68.3"
"@hmscore/react-native-hms-push": "6.5.0-300",

**Comment by Xuejiao-Shi** [comment]
Check whether the sent message is a data messages. When the app is in background or killed state, the [onRemoteMessageReceived](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-References-V1/rnhms-push-event-0000001050155858-V1#section106961656183919) handler will not be called when receiving data messages.

For more details, check [this docs](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides-V1/receivedatamsgkilled-0000001058551962-V1).

**Comment by Daha62** [comment]
Thank you, I've placed the same link already.

It seemed that com.huawei.hms.rn.push.remote.HmsPushMessageService is not started. Do I need to insert something to AndroidManifest?

**Comment by Daha62** [comment]
Oh, data-only is working, thank u.
