### ISSUE TITLE
Can we update maven plugin in Android to use "maven-publish"

### ISSUE THREAD

**Issue by vinaykaitha** [HMS-Core/hms-react-native-plugin#222]
The Maven plugin in the [SafetyDetect Package]( https://github.com/HMS-Core/hms-react-native-plugin/blob/master/react-native-hms-safetydetect/android/build.gradle) is old and deprecated. It does not work(compile) with any of the new Gradle versions.

Can we please update it to **apply plugin: 'maven-plugin'**

Right now I can make it work by manually changing it after installing the package, but will face the same issue when installing fresh, like in case of pipelines.

**Comment by ozcanozgur** [comment]
Hi @vinaykaitha,

"maven-publish" issue has been resolved with the latest version(6.4.0-301) of **Safety Detect** plugin. You can find it at [npm](https://www.npmjs.com/package/@hmscore/react-native-hms-safetydetect).
