### ISSUE TITLE
[Map] show direction on the map

### ISSUE THREAD

**Issue by megaacheyounes** [HMS-Core/hms-react-native-plugin#24]
Hi,

is there a way to show directions on the map between two coordinates, which can be achieved for google map with this library: https://github.com/bramus/react-native-maps-directions

desired result: 
![](https://user-images.githubusercontent.com/213073/33188062-efc86e24-d096-11e7-87eb-6925291bc809.png)

thank

**Comment by utarit** [comment]
Hi, unfortunately hms maps don't have this functionality in default.

**Comment by utarit** [comment]
HMS maps plugin doesn't have a default directions feature. I don't if any library that allows show directions like the library you linked. I think you should get the path data from a directions API and draw the path using polyline by yourself.
