### ISSUE TITLE
Icon in Android app not working with @hmscore/react-native-hms-ml

### ISSUE THREAD

**Issue by breeedly** [HMS-Core/hms-react-native-plugin#240]
Currently I have an application in production and it works correctly. Speech recognition is being implemented in the app, so the following package was installed:
```
"@hmscore/react-native-hms-ml": "^3.5.0-301"
```

The following versions are installed in the application
```
"react": "17.0.2",
"react-native": "0.67.4"
```

JDK:
openjdk 11.0.16.1 2022-07-19 LTS
OpenJDK Runtime Environment Zulu11.58+23-CA (build 11.0.16.1+1-LTS)
OpenJDK 64-Bit Server VM Zulu11.58+23-CA (build 11.0.16.1+1-LTS, mixed mode)

It was configured according to the documentation and the voice recognition works, but the application icon no longer recognizes the one it had, but is modified by the default android one when a project is created in react-native
![image](https://user-images.githubusercontent.com/25566805/197605564-da1d80a6-9c53-4fd9-a09b-2d96ae38af9e.png)

The application previously already has the following packages and has worked correctly
```
"@hmscore/react-native-hms-availability": "^5.2.0-300",
"@hmscore/react-native-hms-location": "^5.1.0-303",
"@hmscore/react-native-hms-push": "^5.3.0-304",
```

In addition to this, when generating an apk-release.apk without the package "@hmscore/react-native-hms-ml" the size of the .apk file is 36.8Mb, but when adding this package the apk-release.apk has a size of 177.4Mb

**Comment by xuxiapu** [comment]
@breeedly We tried the ML Demo. The logo. png in the android/app/src/main/res/mimap hdpi directory should not be set as the application icon.

It is determined according to the configuration in the AndroidManifest file:
![image](https://user-images.githubusercontent.com/114389983/197699509-84bd684e-e1f4-47ba-bf77-68b81550f28f.png)

**Comment by breeedly** [comment]
Add the following in android/app/src/main/AndroidManifest.xml, but it still doesn't work:
![image](https://user-images.githubusercontent.com/25566805/197822883-6f9e7c6a-495b-4190-a95c-da66ad2c022c.png)


This is how the directory currently looks

![image](https://user-images.githubusercontent.com/25566805/197821505-213c5c8c-646b-4b23-ad9e-1479d0321b2f.png)

Doing npm uninstall of @hmscore/react-native-hms-ml and commenting out the code where hmscore/react-native-hms-ml was set causes the icon to work correctly again.

**Comment by xuxiapu** [comment]
@breeedly Please provide the demo code for us to locate the problem.

**Comment by breeedly** [comment]
@xuxiapu Sorry for the delay, here is the demo code.
[https://github.com/breeedly/DemoProject](url)

**Comment by xuxiapu** [comment]
@breeedly 
1. The problem of icon change has nothing to do with the HMSCore ML plug-in.
2. To change the icon, you need to configure the IC_ launcher.xml.
![image](https://user-images.githubusercontent.com/114389983/201030162-bb61475b-f3a1-419b-a5e5-6edf65ced4ce.png)
References are as follows:
<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
  <background android:drawable="@mipmap/ic_launcher_adaptive_back"/>
  <foreground android:drawable="@mipmap/ic_launcher_adaptive_fore"/>
</adaptive-icon>
And configure corresponding pictures, such as:
![image](https://user-images.githubusercontent.com/114389983/201030425-3a29d2c4-a4a4-4f2d-a65a-92070e171f09.png)

**Comment by breeedly** [comment]
@xuxiapu  thanks for the support, the icon works correctly again.
