### ISSUE TITLE
HMSMarker does not render children components as the icon

### ISSUE THREAD

**Issue by megaacheyounes** [HMS-Core/hms-react-native-plugin#246]
Hi guys,

Let me start with an example: using [react-native-maps](https://github.com/react-native-maps/react-native-maps) I can render components as the icon of the marker, as shown in this example.
```jsx
export default function RNDevsMarker() {
  return (
    <Marker>
      <View style={styles.markerIconContainer}>
        <View style={styles.markerBg}>
          <Image
            style={styles.markerImage}
            source={{ uri: "https://reactnative.dev/img/tiny_logo.png" }}
          />
          <View style={styles.markerTextContainer}>
            <Text style={styles.markerText}>React native</Text>
            <Text style={styles.markerText}>234 developers interested</Text>
          </View>
        </View>
        <View style={styles.arrowDown} />
      </View>
    </Marker>
  );
}

const styles = StyleSheet.create({
  markerIconContainer: { backgroundColor: 'transparent', width: 250 },
  arrowDown: {
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderLeftWidth: 8,
    borderRightWidth: 8,
    borderBottomWidth: 16,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: '#A020F0',
    alignSelf: 'center',
    transform: [{ rotate: '180deg' }],
  },
  markerBg: {
    flexDirection: 'row',
    backgroundColor: '#A020F0',
    borderRadius: 50,
    paddingHorizontal: 5,
    paddingVertical: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  markerTextContainer: {
    flexDirection: 'column',
    marginLeft: 5,
    marginRight: 5,
    flexGrow: 1,
    textAlign: 'center',
  },
  markerText: {
    marginTop: 0,
    fontSize: 14,
    fontWeight: 'bold',
    textAlign: 'center',
    color: 'white',
  },
  markerImage: {
    height: 40,
    width: 40,
    borderRadius: 50,
  },
});
```
when running the app,  we get this marker `<RNDevsMarker/>` drawn on Google Maps `<Map/>` as shown here:
![marker_icon](https://user-images.githubusercontent.com/36759976/199713868-bd3b0b03-d918-4352-8db3-97894666e61d.PNG)

but when I try to do the same with `<HMSMarker/>` , Huawei Map `<HMSMap/>` renders the default marker and ignores all children components inside `<HMSMarker/>`!

Currently the only way that you provide to customize `HMSMarker` is by using the attribute `icon`, which is not convenient when we want to render complex or dynamic markers.

what I want is described [here](https://github.com/react-native-maps/react-native-maps/blob/master/docs/marker.md#children-components):
> Children components can be added within a Marker and rendered content will replace the marker symbol. This is a way of creating custom markers and allowing use of native SVGs, example: 
```jsx
<Marker ...>
 <View style={{backgroundColor: "red", padding: 10}}>
   <Text>this will be the markers symbol/icon</Text>
 </View>
</Marker>
```

Please let me know if there's a way to get this to work like google maps, or consider this a Feature Request and implement it :)

Thanks!

**Comment by xuxiapu** [comment]
@megaacheyounes Dear developer,
How are the icons on the left side of the map displayed? Is the UI control added in the XML layout file? Can you provide the relevant documents? It is better to have a simple Demo.
![image](https://user-images.githubusercontent.com/114389983/200243932-7e238bcf-b442-40f9-aadb-4358a945fc6c.png)

**Comment by i01000101** [comment]
Hi @megaacheyounes

The React Native Map Plugin of HMS Core is a wrapper of native Huawei Map SDK and mimics its properties and usage in classes such as HMSMarker. Unfortunately for the time being, rendering children components inside HMSMarker is not a feature for the RN Map Plugin.

You can use `title` and `snippet` props to show a text and a title to user when marker clicked. Maybe this will serve your purpose.

For detailed information, you may also check the official [documentations](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-References/marker-0000001051150162) to see what you can do with HMSMarker.

The feature requests similar to this one is valuable for us, thus we will definetly consider to develop it in our future releases. Meanwhile you may also [submit a ticket online](https://developer.huawei.com/consumer/en/support/feedback/) for feature requests to native SDKs.

Thank you for your interest in our plugins.
