### ISSUE TITLE
[react-native-hms-health] Manifest merger failed with multiple errors, see logs

### ISSUE THREAD

**Issue by Poovit-B** [HMS-Core/hms-react-native-plugin#247]
**Environment**
 - "react-native": "0.70.4",
 - "@hmscore/react-native-hms-health": "^6.7.0-300"

**Description**

I am trying to use react-native-hms-health package but when i try to build my app i am getting this error:

![image](https://user-images.githubusercontent.com/61401085/200520656-d6c81394-d115-4d9c-bd15-353b21edfa43.png)

**Build.gradle**

![code](https://user-images.githubusercontent.com/61401085/200757628-17ae9888-f43c-4b18-98a0-161326b35570.png)

**Comment by xuxiapu** [comment]
@Poovit-B Thank you for your feedback. We have understood the problem and expect to update the version next week. You can also add android: exported="true" or android: exported="false" to the service first.
![image](https://user-images.githubusercontent.com/114389983/200791160-5bd58c7b-5e50-41bc-adb2-71ca2d5dbfb4.png)
https://github.com/HMS-Core/hms-react-native-plugin/blob/master/react-native-hms-health/android/src/main/AndroidManifest.xml

**Comment by xuxiapu** [comment]
Hi,@Poovit-B,react-native-hms-health has been upgraded to the latest SDK version(6.7.0.301) in which this issue had been resolved. You can find it at the [link](https://github.com/HMS-Core/hms-react-native-plugin/issues/247).
