### ISSUE TITLE
[Map] Scroll behaviour inside ScrollView

### ISSUE THREAD

**Issue by ymc-thzi** [HMS-Core/hms-react-native-plugin#25]
Does the map support the feature that scrolling from an outbounding ScrollView is disabled while scrolling inside the MapView?
Google and Apple Maps support this out of the box. If you move around the map the ScrollView is fixed. The HMS map you cannot move if it is inside a ScrollView. Very little and laggy from left to right but not up and down.
Is there a setting I am missing? Or do I have to build this by my own checking the "onCameraMove" callback?

**Comment by utarit** [comment]
The only solution I can think of is disabling ScrollView while interacting with the map. For instance the code below worked for me

```jsx
export default function App() {
  const [mapActive, setMapActive] = useState(false);
  return (
    <>
      <ScrollView scrollEnabled={!mapActive} style={{padding: 16}}>
        <View style={{padding: 16, backgroundColor: "yellow", marginBottom: 8}}>
          <Text>This is a View</Text>
        </View>
        <View style={{padding: 16, backgroundColor: "yellow", marginBottom: 8}}>
          <Text>This is a View</Text>
        </View>
        <MapView
          mapType={1}
          style={{height: 200, marginBottom: 8}}
          onCameraIdle={() => {
            console.log("Idle");
            setMapActive(false);
          }}
          onCameraMove={() => {
            console.log("Move");
            setMapActive(true);
          }}
        />
        <View style={{padding: 16, backgroundColor: "yellow", marginBottom: 8}}>
          <Text>This is a View</Text>
        </View>
        <View style={{padding: 16, backgroundColor: "yellow", marginBottom: 8}}>
          <Text>This is a View</Text>
        </View>
      </ScrollView>
    </>
  );
}
```

**Comment by ymc-thzi** [comment]
Thanks, this is what I meant by building it by my own.

**Comment by ymc-thzi** [comment]
Is there any way to speed up the idle time event? If I moved the map it takes about 7 seconds until it gets fired. So the app seems stucked for 7 sec.
Maybe it is possible to set it as an attribute here HuaweiMap.OnCameraIdleListener?

**Comment by liho00** [comment]
This should be a feature request, pls reopen it @Mike-mei , as the Author said Google and Apple Maps ([React Native Map](https://github.com/react-native-maps/react-native-maps)) support this out of the box.

**Comment by liho00** [comment]
> ```js
> export default function App() {
>   const [mapActive, setMapActive] = useState(false);
>   return (
>     <>
>       <ScrollView scrollEnabled={!mapActive} style={{padding: 16}}>
>         <View style={{padding: 16, backgroundColor: "yellow", marginBottom: 8}}>
>           <Text>This is a View</Text>
>         </View>
>         <View style={{padding: 16, backgroundColor: "yellow", marginBottom: 8}}>
>           <Text>This is a View</Text>
>         </View>
>         <MapView
>           mapType={1}
>           style={{height: 200, marginBottom: 8}}
>           onCameraIdle={() => {
>             console.log("Idle");
>             setMapActive(false);
>           }}
>           onCameraMove={() => {
>             console.log("Move");
>             setMapActive(true);
>           }}
>         />
>         <View style={{padding: 16, backgroundColor: "yellow", marginBottom: 8}}>
>           <Text>This is a View</Text>
>         </View>
>         <View style={{padding: 16, backgroundColor: "yellow", marginBottom: 8}}>
>           <Text>This is a View</Text>
>         </View>
>       </ScrollView>
>     </>
>   );
> }
> ```

tried this in the latest @hmscore/react-native-hms-map,  the map is difficult to be scrolled in the ScrollView, sad for Huawei User haha, I had to deliver the app in coming weeks, this will delivery bad UX to the Huawei User, Please take caution on this.

**Comment by anyamiletic** [comment]
@aktug is there any progress on this issue? Setting `scrollEnabled={false}` every time the camera is Idle is really not a good solution, especially since slowly moving the map will send multiple `Move -> Idle` calls. Also, starting to move the map vertically (in case of vertical ScrollView) doesn't work most of the time, giving a really poor UX.

**Comment by trung1051996** [comment]
Hi All, 
We has any update for `scrollEnabled={false}`, as @anyamiletic mentioned, `every time the camera is Idle is really not a good solution`, it is not smooth from my side
