### ISSUE TITLE
Building the same thing as the plugins in Flutter for Huawei plugins 

### ISSUE THREAD

**Issue by knana1662** [HMS-Core/hms-react-native-plugin#250]
Please does this plugin have the same plugins as the one's in Flutter for Huawei plugins?

**Comment by xuxiapu** [comment]
@knana1662 Flutter is in this link.
https://github.com/HMS-Core/hms-flutter-plugin

Please refer to the link to learn how to use plug-ins: https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/flutter-intro-0000001054787256
