### ISSUE TITLE
A problem occurred configuring project ':hmscore_react-native-hms-analytics'.

### ISSUE THREAD

**Issue by Daha62** [HMS-Core/hms-react-native-plugin#253]
Good day sometimes I facing with problem:

A problem occurred configuring project ':hmscore_react-native-hms-analytics'.
> Could not resolve all files for configuration ':hmscore_react-native-hms-analytics:classpath'.
   > Could not download asm-commons-7.0.jar (org.ow2.asm:asm-commons:7.0)
      > Could not get resource 'https://jcenter.bintray.com/org/ow2/asm/asm-commons/7.0/asm-commons-7.0.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/ow2/asm/asm-commons/7.0/asm-commons-7.0.jar'.
            > jcenter.bintray.com
   > Could not download txw2-2.3.1.jar (org.glassfish.jaxb:txw2:2.3.1)
      > Could not get resource 'https://jcenter.bintray.com/org/glassfish/jaxb/txw2/2.3.1/txw2-2.3.1.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/glassfish/jaxb/txw2/2.3.1/txw2-2.3.1.jar'.
            > jcenter.bintray.com

Not only with analytics package, also can fall with any

**Environment:**
    "@hmscore/react-native-hms-analytics": "6.3.2-302",
    "@hmscore/react-native-hms-push": "6.5.0-300",
    "@react-native-agconnect/crash": "1.2.0",
    "react-native": "0.70.5",
    
    
    Any ideas?

**Comment by xuxiapu** [comment]
Dear developer,

We suspect that this may be due to the configuration failure caused by your network problem. You can check whether there is a problem with the network you are using, or the proxy you are using. This is why the two links cannot be downloaded.

**Comment by Daha62** [comment]
Thank you!
Ah, thats happened because of jcenter got 403 error, moved to mavenCentral

**Comment by Daha62** [comment]
oh, it was because of jcenter, thank you!
