### ISSUE TITLE
react-native-hms-push  in processDebugMainManifest FAILED

### ISSUE THREAD

**Issue by kittipat3699** [HMS-Core/hms-react-native-plugin#254]
Hi guys,
i got error, when i run android

` Task :app:processDebugMainManifest FAILED
[:react-native-hms-push] /Users/Desktop/node_modules/@hmscore/react-native-hms-push/android/build/intermediates/library_manifest/debug/AndroidManifest.xml Warning:
        Package name 'com.huawei.hms.rn.push' used in: :react-native-hms-push, :hmscore_react-native-hms-push.`

Please let me know if there's a way to get this to work 

Thanks!

**Comment by i01000101** [comment]
Hi @kittipat3699, we couldn't reproduce your issue with our demo application. Can you please share a detailed log and minimal reproducible project to investigate the issue further.

Thank you for your interest.
