### ISSUE TITLE
[request] Upgrade Ads SDK to support all android devices

### ISSUE THREAD

**Issue by megaacheyounes** [HMS-Core/hms-react-native-plugin#255]
Hi,

Currently Ads Kit plugin is using Ads lite SDK, which works on Huawei devices only: https://github.com/HMS-Core/hms-react-native-plugin/blob/master/react-native-hms-ads/android/build.gradle#L52)

```groovy
    implementation 'com.huawei.hms:ads-lite:13.4.54.300'
```

Please consider replacing it with ads prime SDK (full SDK) which supports all android devices, not just Huawei.

```groovy
  implementation 'com.huawei.hms:ads-prime:3.4.58.301'
```

**Comment by xuxiapu** [comment]
@megaacheyounes Dear developer,
You can build Replace the "ads lite SDK" in the gradle file with the "ads prime SDK", and then try again. If you have other questions, please contact us.

**Comment by UgurBas** [comment]
Hi @megaacheyounes ,
You can use [Ads Prime](https://github.com/HMS-Core/hms-react-native-plugin/tree/master/react-native-hms-adsprime) kit to solve this problem.

Thank you for your interest.

**Comment by megaacheyounes** [comment]
I didn't know this plugin existed, thanks for the suggestions.

Does Ads Prime plugin and Ads plugin have the same APIs (functions), in other word, is it a drop-in replacements?
or moving to Ads Prime require code changes?

**Comment by UgurBas** [comment]
You are welcome. No, you don't need to make any code changes. You can use it with the same codes.
