### ISSUE TITLE
Error is coming in initiallising  HMSSDK

### ISSUE THREAD

**Issue by EduarnoTech** [HMS-Core/hms-react-native-plugin#256]
I have installed the npm package of 100ms for react-native , but as soon as I am running the app locally there showing an error"Un

**Comment by EduarnoTech** [comment]
"Unexpected identifier '_reactNativeHms' , Expected ';' after variable declaration    no stack

**Comment by EduarnoTech** [comment]
Please help

**Comment by xuxiapu** [comment]
@EduarnoTech Dear developer,
Which plug-in of hms-reactive-native-plugin do you integrate? It is recommended that you refer to the guidance for integration. Link:https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/rn-intro-0000001050975015
