### ISSUE TITLE
[MAP] Prevent marker click automatic moving

### ISSUE THREAD

**Issue by ymc-thzi** [HMS-Core/hms-react-native-plugin#26]
When I click on a marker even doing nothing like 
`<Marker
...
onClick={() => console.log('press')}
/>
`
the map is moving. Always so that the clicked marker moves to the middle of the screen. Is there a way to disable that?

**Comment by utarit** [comment]
Hi, this is the default action and unfortunately you cannot override it right now. We already implemented a prop about this problem which prevents the default action and it will be released in the next version of the map.

**Comment by aktug** [comment]
Hi @ymc-thzi 
This missing feature has been implemented and waiting to release.
The next version **5.0.3.301** will be published at end of the November 👍
