### ISSUE TITLE
react-native-cli compilation error

### ISSUE THREAD

**Issue by HardSLL** [HMS-Core/hms-react-native-plugin#261]
Hello. I try build react-native app, but when compiling this error
![image](https://user-images.githubusercontent.com/91246556/213287993-36a08621-fb96-4319-981b-d50350068f89.png)

build.gradle
buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33

        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"
    }
    repositories {
        google()
        mavenCentral()
        maven {url 'https://developer.huawei.com/repo/'}
    }
    dependencies {
        classpath("com.android.tools.build:gradle:7.3.1")
        classpath("com.facebook.react:react-native-gradle-plugin")
    }
}

Help me figure out this question, what am I doing wrong?

**Comment by i01000101** [comment]
Hello @HardSLL, you also need to add `maven { url 'https://developer.huawei.com/repo/' }` to "repositories" block in "allprojects" block of your build.gradle file.

You can follow all of the integration steps in our [guide document](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides-V1/integrating-sdk-0000001050034173-V1).

Thanks for your interest.
