### ISSUE TITLE
[react-native-hms-push] build fails with new react-native version

### ISSUE THREAD

**Issue by GabrielDierks** [HMS-Core/hms-react-native-plugin#274]
**Description**

After updating our dependencies the build fails with the following error:

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeProjectDexDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingTaskDelegate
   > There was a failure while executing work items
      > A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingWorkAction
         > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
           Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
           Type devmenu.com.swmansion.common.GestureHandlerStateManager is defined multiple times: /Users/xx/root/mobile-app/android/app/build/intermediates/mixed_scope_dex_archive/debug/out/badfdc771dfffcdbaaca8e050ce09a4aca67908ae89b610d644062833a0ee1ad_1.jar:classes.dex, /Users/xx/root/mobile-app/android/app/build/intermediates/mixed_scope_dex_archive/debug/out/dcd30cd0bd8d4cb28c5ec273bf019d7e86245980a667359bd40e8cb5d420f649_1.jar:classes.dex

**Environment**
 - Platform: React-Native
     "react-native": "0.71.7",
    "react-native-reanimated": "~2.14.4",
    "react-native-gesture-handler": "~2.9.0",

 - Kit: @hmscore/react-native-hms-push
 - Kit Version: 6.7.0-300
 - Node Version 16.x

**Comment by ajqtech** [comment]
@GabrielDierks From which version you upgraded to 0.71.7 ? Thanks

**Comment by GabrielDierks** [comment]
"react-native": "0.68.2",
    
    While further investigating yesteday the issue seems to be related to:
        "expo-dev-client": "~2.1.5",
        
This package is using a vendored version of "react-native-gesture-handler" which is clashing with "react-native-hms-push".

**Comment by GabrielDierks** [comment]
Has been fixed with "expo-dev-client": "2.3.0"
