### ISSUE TITLE
Can the latest tag be created for the current open source repository?

### ISSUE THREAD

**Issue by clancytom** [HMS-Core/hms-react-native-plugin#285]
Currently, there is only one tag v5.10.0-300 in the code repository. No new tag has been created for more than two years. Can we use this software to create a new tag?

**Comment by ozkulbeng** [comment]
Hi @clancytom 

We update our plugins as batches, which means we may update a couple of plugins in a month with their own version numbers. All of our monthly releases have an internal common version number, yet it is not related to plugins or their versions. If you explain the necessity of tags in detail we will definitely consider applying it to our repository. 

Thank you for your interest in our plugins.
