### ISSUE TITLE
Map not showing in React Native Expo 

### ISSUE THREAD

**Issue by Jocrod1** [HMS-Core/hms-react-native-plugin#306]
**Description**
The Map not showing in React Native + Expo. 

**Expected behavior**
Show PetalMaps

**Current behavior**
PetalMaps not showing

**Screenshots**
If applicable, add screenshots to help explain your issue
<img src="https://github.com/HMS-Core/hms-react-native-plugin/assets/38761991/2512f826-5017-4791-82e7-dc243ae41782" alt="appScreenshot" width="300"/>
<img src="https://github.com/HMS-Core/hms-react-native-plugin/assets/38761991/5db92785-f713-4432-9ee2-032a5a4b1661" alt="InspectorScreenshot" width="300"/>

**Logs**
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.

**Environment**
 - Platform: [React-Native + Expo]
 - Kit: [Map/HMS-Available]
 - Kit Version [6.11.0-304 / 6.11.0-301 ]
 - OS Version [Android 11]
    "@hmscore/react-native-hms-availability": "^6.11.0-301",
    "@hmscore/react-native-hms-map": "^6.11.0-304",
    "expo": "~49.0.15",
    "expo-dev-client": "~2.4.12",
    "expo-status-bar": "~1.6.0",
    "react": "18.2.0",
    "react-native": "0.72.6",
    "expo-splash-screen": "~0.20.5"

**Other**
# [Repro app project](https://github.com/Jocrod1/ExpoHMSMapsRepro)

**Comment by Jocrod1** [comment]
Map kit is enabled, agconnect-services.json is loaded, the packageNames matchs with the app, the SHA-256 certificate fingerprint is the same on appGallery, the app is signed Properly.

But is not even showing the PetalMaps Logo

**Comment by ozkulbeng** [comment]
Hello @Jocrod1 
Unfortunately, Huawei HMS React Native plugins do not have Expo support currently.
