### ISSUE TITLE
react-native-hms-iap [Question]

### ISSUE THREAD

**Issue by cristea2017** [HMS-Core/hms-react-native-plugin#32]
**Description**
After integrating `react-native-hms-iap` we have trouble with app verification. 

when i test on : real device , cloud debbuging with realdevice/simulator all works ideally, when my app is verified by Huawei they cant buy anythink.

**Video**
- when Huawei tester tests
https://cloud.mail.ru/public/4bWW%2F3Vmkkiw6X

- when i tests
https://cloud.mail.ru/public/AE7E%2F2e1SK6Ne4
 

So my question is : what i am doing wrong ? any suggestion ? is this mystic ?  Thanks for any help!

**Comment by rozeridilar** [comment]
As I see in the video, there is nothing wrong with the integration of the HMS IAP. 
To double-check please make sure that you have completed all the steps in this [video](https://www.youtube.com/watch?v=aiPFxiiUz_U&list=PL5K4yoEaZLIA6FOrDkBE4gdnoc0lDnP6q&ab_channel=CodingGoals) or [documentation](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/integrating-sdk-0000001050726210).

After checking the integration of the React Native HMS IAP, please make sure that you have installed HMS Core (APK) of the **latest** version and you have a huawei account connected to your huawei test device. 
For subscriptions, has the test account bought another product from the same subscription group previously? If so, please check the further information regarding subscriptions including **switching between subscriptions** part in  [here](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/subscription-functions-0000001051086186).

**Comment by cristea2017** [comment]
> As I see in the video, there is nothing wrong with the integration of the HMS IAP.
> To double-check please make sure that you have completed all the steps in this [video](https://www.youtube.com/watch?v=aiPFxiiUz_U&list=PL5K4yoEaZLIA6FOrDkBE4gdnoc0lDnP6q&ab_channel=CodingGoals) or [documentation](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/integrating-sdk-0000001050726210).
> 
> After checking the integration of the React Native HMS IAP, please make sure that you have installed HMS Core (APK) of the **latest** version and you have a huawei account connected to your huawei test device.
> For subscriptions, has the test account bought another product from the same subscription group previously? If so, please check the further information regarding subscriptions including **switching between subscriptions** part in [here](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/subscription-functions-0000001051086186).

ok, thx
