### ISSUE TITLE
HMS won't accept apply in .gradle file in react-version 0.74.1 

### ISSUE THREAD

**Issue by mahermalhem** [HMS-Core/hms-react-native-plugin#335]
**Description**
i am trying to impl this pkg and it's features for sending notifications 
https://www.npmjs.com/package/@hmscore/react-native-hms-push?activeTab=versions

on RN-V 0.74.1 and each time i write 
apply plugin: "com.huawei.agconnect"

it wont sync

After i tried manual installation 

* What went wrong:
A problem was found with the configuration of task ':react-native-hms-push:copyDebugJniLibsProjectOnly' (type 'LibraryJniLibsTask').
  - Gradle detected a problem with the following location: '/Users/mahermalhem/Documents/newRepo/new-jo-academy-app/node_modules/@hmscore/react-native-hms-push/android/build/intermediates/merged_native_libs/debug/out'.
    
    Reason: Task ':react-native-hms-push:copyDebugJniLibsProjectOnly' uses this output of task ':hmscore_react-native-hms-push:mergeDebugNativeLibs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
    
    Possible solutions:
      1. Declare task ':hmscore_react-native-hms-push:mergeDebugNativeLibs' as an input of ':react-native-hms-push:copyDebugJniLibsProjectOnly'.
      2. Declare an explicit dependency on ':hmscore_react-native-hms-push:mergeDebugNativeLibs' from ':react-native-hms-push:copyDebugJniLibsProjectOnly' using Task#dependsOn.
      3. Declare an explicit dependency on ':hmscore_react-native-hms-push:mergeDebugNativeLibs' from ':react-native-hms-push:copyDebugJniLibsProjectOnly' using Task#mustRunAfter.
    
    For more information, please refer to https://docs.gradle.org/8.6/userguide/validation_problems.html#implicit_dependency in the Gradle documentation.

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

* Exception is:
org.gradle.internal.execution.WorkValidationException: A problem was found with the configuration of task ':react-native-hms-push:copyDebugJniLibsProjectOnly' (type 'LibraryJniLibsTask').
  - Gradle detected a problem with the following location: '/Users/mahermalhem/Documents/newRepo/new-jo-academy-app/node_modules/@hmscore/react-native-hms-push/android/build/intermediates/merged_native_libs/debug/out'.
    
    Reason: Task ':react-native-hms-push:copyDebugJniLibsProjectOnly' uses this output of task ':hmscore_react-native-hms-push:mergeDebugNativeLibs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
    
    Possible solutions:
      1. Declare task ':hmscore_react-native-hms-push:mergeDebugNativeLibs' as an input of ':react-native-hms-push:copyDebugJniLibsProjectOnly'.
      2. Declare an explicit dependency on ':hmscore_react-native-hms-push:mergeDebugNativeLibs' from ':react-native-hms-push:copyDebugJniLibsProjectOnly' using Task#dependsOn.
      3. Declare an explicit dependency on ':hmscore_react-native-hms-push:mergeDebugNativeLibs' from ':react-native-hms-push:copyDebugJniLibsProjectOnly' using Task#mustRunAfter.

**Comment by ryskin** [comment]
same, please help

**Comment by itsmeshusha** [comment]
Have anybody solution?

**Comment by GennadySX** [comment]
Edit `android/app/build.gradle` (NOT `android/build.gradle`) and add:

```
afterEvaluate {
    android.applicationVariants.all { variant ->
        def targetName = variant.name.capitalize()
        def dependerTask = tasks.findByName("generate${targetName}ResValues")
        if (dependerTask) {
            dependerTask.dependsOn("package${targetName}Resources")
        }
    }
}
```

**Comment by omarabualhija** [comment]
now it is working with me on` 0.74.2 ` 

what i did !

first one download the library 

  ` yarn add @hmscore/react-native-hms-push`
   
   you can use `6.12.0-301` or `6.12.0-300`    there is no difference between them
   
   see` https://developer.huawei.com/consumer/en/doc/HMS-Plugin-Guides-V1/version-change-history-0000001050766267-V1 `
   
  `android/build.gradle`  
  
  inside  `repositories` block add 
  
  `  maven { url 'https://developer.huawei.com/repo/' }  `. 
        
        and in `dependencies` add
        
` classpath 'com.huawei.agconnect:agcp:1.9.1.300' `

     and at the bottom of the file add 
        
```
        allprojects {
  repositories {
          google()
        mavenCentral()
    maven { url 'https://developer.huawei.com/repo/' }
  }
}

apply plugin: "com.huawei.agconnect"

```

   your file shod be like this 
   
<img width="683" alt="Screenshot 2024-07-06 at 9 56 48 AM" src="https://github.com/HMS-Core/hms-react-native-plugin/assets/71391078/c9fa639d-f563-430b-a80d-e2020d3704b4">


`android/settings.gradle`. add 

`include ':react-native-hms-push'
project(':react-native-hms-push').projectDir = new File(rootProject.projectDir, '../node_modules/@hmscore/react-native-hms-push/android')`


<img width="1084" alt="Screenshot 2024-07-06 at 9 58 48 AM" src="https://github.com/HMS-Core/hms-react-native-plugin/assets/71391078/5a76a7ab-ea81-4d8c-a6be-40d61cfe9cab">


finally in `android/app/build.gradle`. inside `dependencies`  add 

` implementation "com.huawei.hms:push:6.12.0.300"`


<img width="1084" alt="Screenshot 2024-07-06 at 10 00 24 AM" src="https://github.com/HMS-Core/hms-react-native-plugin/assets/71391078/e812c538-42ba-4b3d-8f49-3108f23abba6">

then run your app on android studio  
it shod works fine !

**Comment by mahermalhem** [comment]
@omarabualhija  Thanks, everything went good and worked now even on  0.74.1

don't know what the issue was exactly, i had done same implementaion on the days i was working on
also i have samll comment on setting.gradle file 
always put the 

include ':react-native-hms-push' 
project(':react-native-hms-push').projectDir = new File(rootProject.projectDir, '../node_modules/@hmscore/react-native-hms-push/android')

before the

apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)

Closed ...
