### ISSUE TITLE
Can't get Received Push Notification payload

### ISSUE THREAD

**Issue by maxfelipe** [HMS-Core/hms-react-native-plugin#34]
**Description**
When listening to onNotificationOpenedApp I expect to see the payload I send on my message

**Expected behavior**
I expect to see the payload of the message I sent

**Current behavior**
The received message object is empty

**Logs**
This is the payload I'm sending through   https://push-api.cloud.huawei.com/v1/XXXXX/messages:send

{
    "validate_only": false,
    "extra" : {"e1" : 1},
    "message": {
        "extra2" : {"e2" : 1},
        "data" : "prueba",
        "notification": {
            "title": "message title",
            "body": " message body",
            "Extra1" : "Extra1,"
        },
        "android": {
            "extra3" : {"e3" : 3},
            "notification": {
                "extra4" : {"e4" : 4},
                "title": "Noti in Noti title",
                "body": "Mi cuerpo TOPIC",
                "click_action": {
                    "type": 1,  
                    "intent" : "intent"
                }
            }
        },        "topic":  "XXX__XXX"
    }
}

And this is the JSON response I see when running this code
  HmsPushEvent.onNotificationOpenedApp((result)=>{
    console.log("NOTIFICATION_OPENED_EVENT",JSON.stringify(result));
  })

NOTIFICATION_OPENED_EVENT {"uriPage":null,"extras":{"_push_cmd_type":"cosa","_push_msgid":"-1778066760","_push_notifyid":415863099},"remoteMessage":{"Link":"null","collapseKey":null,"ClickAction":null,"NotifyId":"0","contents":"0","When":"null","token":null,"isDefaultSound":"true","isDefaultVibrate":"true","ImageUrl":"null","bodyLocalizationArgs":"null","Ticker":null,"Tag":null,"Sound":null,"isLocalOnly":"true","data":null,"body":null,"urgency":"2","titleLocalizationKey":null,"originalUrgency":"2","vibrateConfig":"null","messageId":null,"dataOfMap":"{}","BadgeNumber":"null","sentTime":"0","intentUri":null,"isDefaultLight":"true","isAutoCancel":"true","from":null,"ChannelId":null,"Color":null,"titleLocalizationArgs":"null","to":null,"sendMode":"0","bodyLocalizationKey":null,"Importance":"null","icon":null,"messageType":null,"ttl":"86400","LightSettings":"null","receiptMode":"0","visibility":"null","title":null}}

As you can see, the whole object is null, instead of having any of the payload that I was sent

**Environment**
 - Platform: [e.g. React-Native/Cordova/Flutter/Xamarin]
 - Kit: Push
 - Kit Version 5.0.2-301
 - OS Version Android 11
 - Android Studio version4.1

**Other**

**Comment by aktug** [comment]
Hello @maxfelipe;
Push SDK does not expose the message payloads/contents, we can access only these **uriPage**, **extras**, and **remoteMessage**, and as you see; remoteMessage's values are all null.

**Comment by aktug** [comment]
My suggestion as a workaround is;
You can send data message instead of notification thus you can access all properties of data message then use that values with LocalNotification feature.

**Comment by maxfelipe** [comment]
So, why is the remoteMessage field null? Shouldn't it have what I send with the push message? How do I get something to be read on the client? Where would I have to set "uriPage" or "extras" on the JSON I send to the push server?

**Comment by aktug** [comment]
This is **extras** part:
![image](https://user-images.githubusercontent.com/20382405/99060607-532f9b00-25b1-11eb-8237-c734064708ed.png)
This is **uriPage** part:
![image](https://user-images.githubusercontent.com/20382405/99060631-5c206c80-25b1-11eb-9c96-50716bdc3e6a.png)
Rest of them are **remoteMessage** 👍
