### ISSUE TITLE
Question: PushKit with custom "sound" from send API not working??

### ISSUE THREAD

**Issue by chhornponleu** [HMS-Core/hms-react-native-plugin#35]
**Description**
Sending push notification, with custom sound, always play default sound

**Expected behavior**
The notification sound should be the custom sound

**Current behavior**
The notification play default sound

**Screenshots**
I place sound inside  `/res/raw`
![image](https://user-images.githubusercontent.com/14964945/98771762-c1d8f100-2417-11eb-9238-f3b4b0b75678.png)

**Environment**
 - Platform: [e.g. React-Native/Cordova/Flutter/Xamarin]
 - Kit: [e.g. Push/Map/Ads/Account/IAP]
 - Kit Version [e.g. 5.0.3]
 - OS Version [e.g. Android 11]
 - Android Studio version (if applicable) [e.g. 4.1]
 - Platform version (if applicable)
 - Node Version (if applicable)
 - Your Location/Region (if applicable) 

**Other**
Data sent to **https://push-api.cloud.huawei.com/v1/[appid]/messages:send**
```
{ 
    "message": {
        "notification": {
            "title": "Test title",
            "body": "Test body..."
        },
        "token": [
            "My device token", 
        ],
        "android": {
            "notification": {
                "title": "Test title",
                "body": "Test body...",
                "click_action": {
                    "type": 3
                },
                "default_sound": false,
                "sound": "storedispatch"
            }
        }
    }
}
```

**Comment by aktug** [comment]
Hello @chhornponleu
Firstly, this question is related to send API not "react-native-hms-push" plugin,

When sending downlink messages;
Custom message notification ringtone, which is valid during channel creation. The ringtone file must be stored in the **/res/raw** directory of an app. For example, the value **/raw/shake** indicates the local ringtone file **/res/raw/shake.xxx** stored in **/res/raw**. Currently, various file formats such as MP3, WAV, and MPEG are supported. If this parameter is not set, the default system ringtone will be used.

**NOTE:**
The ringtone is an attribute of the notification channel. Therefore, a ringtone is valid only if it is set during channel creation. If a ringtone is set after the channel is created, it will not be played and the one set during channel creation is played instead.

For details: https://developer.huawei.com/consumer/en/doc/development/HMSCore-References-V5/https-send-api-0000001050986197-V5

**Comment by chhornponleu** [comment]
>Custom message notification ringtone, which is valid during channel creation.

This make no sense to me. Where, when, how the custom message is being created?? There is no working solution and sample for the issue. 

Please 🙏🙏🙏🙏
I need a working solution.

**You guys just point the issue here and there. Why???**
