### ISSUE TITLE
什么时候能加入ios的支持

### ISSUE THREAD

**Issue by leoxiaoping** [HMS-Core/hms-react-native-plugin#38]
native 文档已经与ios的支持了，rn版什么时候加入ios的支持呢

**Comment by aktug** [comment]
你好 @leoxiaoping 
哪个工具包？

**Comment by leoxiaoping** [comment]
@aktug HMS Scankit

统一扫码服务
https://developer.huawei.com/consumer/cn/doc/development/HMSCore-Guides/ios-version-change-history-0000001050414335

**Comment by aktug** [comment]
iOS 的 Scan Kit 在路线图中. 我们将很快发布新版本的 Scan Kit 与 iOS 支持.
