### ISSUE TITLE
[Map] Marker icon from a Link

### ISSUE THREAD

**Issue by megaacheyounes** [HMS-Core/hms-react-native-plugin#45]
Hello team,

Does marker icon property supports web Urls? if not can you add support for that?
 
```javascript
<Marker 
icon={{ path: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Map_marker.svg/512px-Map_marker.svg.png" }}
/>
```

Also is there a way to scale the icons (increase/decrease the size)?

thanks.

**Comment by megaacheyounes** [comment]
Also cluster icon showing circle with blue color, is there a way to change the cluster icon or change its color??

**Comment by utarit** [comment]
Hi, 
Unfortunately, web urls and changing clustering color are not supported at the moment. We will work for giving web url support for marker icons in further releases.
About scaling, you can use marker animations to scale up/down the marker. However, you can't initialize a default marker with a customized size.
