### ISSUE TITLE
HMS Location: getLastLocation "Result from location kit is null"

### ISSUE THREAD

**Issue by SimonErich** [HMS-Core/hms-react-native-plugin#52]
**Description**
I have implemented the getLastLocation command, exactly and also a little abstracted as in the docs and kept stumbling upon the error "Result from location kit is null" and no result.

This is my code:
```
    /**
     * Returns the geolocation data
     */
    async getGeoLocation(): Promise<HmsGeolocationData> {
        try {
            await HMSLocation.LocationKit.Native.init();

            try {
                await HMSLocation.FusedLocation.Native.requestPermission();
            } catch (e) {
                alert('HMSLocation: Couldnt get location permissions', e);
                HMSLocation.FusedLocation.Native.requestPermission();
            }
        
        } catch (initException) {
            alert("Error while initializing." + initException);
        }
                
        return  HMSLocation.FusedLocation.Native.getLastLocation();
    },
```

I tried to resolve it for a while and then decided to try install another GPS app, because I feared, that something is wrong with my device.
As soon as I installed MAPS.ME (just to test the GPS chip in my phone) everything works perfect on this phone now.
I always get a location perfectly as expected and no problems.

But then I tried to upload the app to the Cloud Debugging instance and there again it doesn't work and return the "Result from location kit is null" error.
I did not change anything on the code.
It seems like I am only getting the last geolocation if it was initiated by another app.

Is there a command to initiate the location myself?
`HMSLocation.LocationKit.Native.init()` returns true from my example as well. (that was my first guess)

Did I miss anything?

**Expected behavior**
The geolocation coordinates should always be returned, even on a fresh phone, that has never accessed GPS coords from a different app.

**Current behavior**
As long as I did not install another app with GPS support I always get "Result from location kit is null".

**Comment by mustafahaluk** [comment]
There are explanations on [android ](https://developer.huawei.com/consumer/en/doc/development/HMSCore-References-V5/fusedlocationproviderclient-0000001050746169-V5#EN-US_TOPIC_0000001050746169__section1167913136559) and  [react-native](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-References/fusedlocation-0000001050043303#EN-US_TOPIC_0000001050140366__section164933173714) document websites about why `getLastLocation()` function returns `null`.

> The promise may return an error message `{"errorCode":810,"errorMessage":"Result from location kit is null."}` in the following scenarios:
> - The location function has never been used.
> - The location function is disabled.
> - The device is restored to factory settings.

> If real-time location is required, you are advised to proactively call `requestLocationUpdatesWithCallback()` instead of `getLastLocation()`. To receive a location once only, you can set `numUpdates` in LocationRequest to `1`.

By the way, `init()` function initializes broadcast receiver within your app and enables [event](https://reactnative.dev/docs/next/native-modules-android#sending-events-to-javascript) mechanisms work with this broadcast receiver.

**Comment by inkCrazy** [comment]
> There are explanations on [android ](https://developer.huawei.com/consumer/en/doc/development/HMSCore-References-V5/fusedlocationproviderclient-0000001050746169-V5#EN-US_TOPIC_0000001050746169__section1167913136559) and [react-native](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-References/fusedlocation-0000001050043303#EN-US_TOPIC_0000001050140366__section164933173714) document websites about why `getLastLocation()` function returns `null`.[在 android ](https://developer.huawei.com/consumer/en/doc/development/HMSCore-References-V5/fusedlocationproviderclient-0000001050746169-V5#EN-US_TOPIC_0000001050746169__section1167913136559) 和 [react-native](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-References/fusedlocation-0000001050043303#EN-US_TOPIC_0000001050140366__section164933173714) 文档网站上有关于 `getLastLocation（）` 函数返回 `null` 的原因的解释。
> 
> > The promise may return an error message `{"errorCode":810,"errorMessage":"Result from location kit is null."}` in the following scenarios:在以下情况下，Promise 可能会返回错误消息 `{"errorCode":810,"errorMessage":"Result from location kit is null."}` ：
> > 
> > * The location function has never been used.从未使用过 location 函数。
> > * The location function is disabled.位置功能已关闭。
> > * The device is restored to factory settings.设备恢复出厂设置。
> 
> > If real-time location is required, you are advised to proactively call `requestLocationUpdatesWithCallback()` instead of `getLastLocation()`. To receive a location once only, you can set `numUpdates` in LocationRequest to `1`.如果需要实时位置信息，建议主动调用 `requestLocationUpdatesWithCallback()` `getLastLocation（），不要使用 getLastLocation（）。` 要仅接收一次位置，您可以将 LocationRequest 中的 `numUpdates` 设置为 `1`。
> 
> By the way, `init()` function initializes broadcast receiver within your app and enables [event](https://reactnative.dev/docs/next/native-modules-android#sending-events-to-javascript) mechanisms work with this broadcast receiver.顺便说一句，`init（）` 函数会初始化应用中的广播接收器，并启用[事件](https://reactnative.dev/docs/next/native-modules-android#sending-events-to-javascript)机制与此广播接收器配合使用。

```
if (Platform.OS === 'android') {
    const locationRequest = {
      priority: HMSLocation.FusedLocation.Native.PriorityConstants.PRIORITY_HIGH_ACCURACY,
      interval: 3,
      numUpdates: 10,
      fastestInterval: 1000.0,
      expirationTime: 200000.0,
      expirationTimeDuration: 200000.0,
      smallestDisplacement: 0.0,
      maxWaitTime: 2000000.0,
      needAddress: false,
      // coordinateType: HMSLocation.Geofence.Native.GeofenceRequestConstants.COORDINATE_TYPE_GCJ_02,
    };
    const locationSettingsRequest = {
      locationRequests: [locationRequest],
      alwaysShow: false, //alwaysShow 属性指示应用程序是否需要某个位置才能继续
      needBle: false, //needBle 属性指示是否需要启用 BLE 扫描
    };

    const reqCode = 1;
    HMSLocation.FusedLocation.Native.requestLocationUpdatesWithCallback(locationRequest)
      .then(res => {
        console.log('requestLocationUpdatesWithCallback', res);
        HMSLocation.FusedLocation.Native.getLastLocation()
          .then(pos => {
            console.log('Last location:', pos);
            const coords = pos;

            // Transform coordinates
            const result = gcoord.transform(
              [coords.longitude, coords.latitude],
              gcoord.WGS84, // Source coordinate system
              targetCoordSystem, // Target coordinate system
            );
            console.log('Transformed Location:', result);

            const transformedLocation = {
              ...coords,
              longitude: result[0],
              latitude: result[1],
              originalCoords: coords,
              coordSystem: targetCoordSystem,
            };

            console.log('Transformed Location:', transformedLocation);

            // Call success callback with transformed location
            onSuccess && onSuccess(transformedLocation);
          })
          .catch(error => {
            Alert.alert('定位失败', error.message || '无法获取当前位置', [{text: '确定'}]);
            onError && onError(error);
            console.log('Failed to get last location', error);
          });
      })
      .catch(err => {
        //{"errorCode":800,"errorMessage":"10101: ARGUMENTS_INVALID"} //参数无效
        console.log('requestLocationUpdatesWithCallback error:', err.message);
      });
  }
```
当我调用requestLocationUpdatesWithCallback的时候，其他手机没问题，华为和荣耀报错：{"errorCode":800,"errorMessage":"10101: ARGUMENTS_INVALID"}
