### ISSUE TITLE
HMS Maps are not rendering in huawei cloud device and hms core installed google play service devices 

### ISSUE THREAD

**Issue by ramasamy11** [HMS-Core/hms-react-native-plugin#53]
I'm trying to use Huawei maps in react native application for android support, After making necessary changes based on hms map kit demo, I'm unable to load the maps in Huawei cloud simulator and hms core with google play service devices as well. I'm able to see only a white screen on the map. Please let me know any changes to be done to resolve the issue.

 - Platform: React-Native 0.63.4 , React 16.13.1
 - Kit: [Map ]
 - Kit Version [5.0.1-300]
 - OS Version [Android 10, Android 11]
 - Android Studio version  [ Android Studio  4.0.1]
 
<img width="562" alt="Screenshot 2020-12-16 at 4 21 49 PM" src="https://user-images.githubusercontent.com/12136368/102448654-9cfc1d00-4058-11eb-89b6-648b578ea9f4.png">
<img width="556" alt="Screenshot 2020-12-16 at 4 11 32 PM" src="https://user-images.githubusercontent.com/12136368/102448666-a6858500-4058-11eb-9fad-e5c03b66888f.png">

**Comment by utarit** [comment]
Hi, 
Can you see the map in other devices? (other than cloud devices and the ones with google play services) 

Also can you also run the native demo in these devices with same configurations (especially agconnect and keystore configurations) so that we can understand the source of the problem?

**Comment by ramasamy11** [comment]
Thanks.  let me check in device

**Comment by ramisalem** [comment]
Did you find a solution for this?

**Comment by tyukesz** [comment]
Same issue here
