### ISSUE TITLE
Unable to set custom notification icon

### ISSUE THREAD

**Issue by mannol** [HMS-Core/hms-react-native-plugin#55]
Hello,

I'm having an issue with setting custom icon on notification popup on android. I've tried both of [these](https://developer.huawei.com/consumer/en/doc/development/HMS-Guides/push-other) approaches (described under section 11.) but the notification popup just keeps using the default icon.

I've also made sure that I'm using a resource located at: `/res/raw/my_icon.png` which, as the name suggests, is a PNG image. I've also tried using various other resources but nothing.

Thanks.

P. S. hms-push version: `"@hmscore/react-native-hms-push": "^5.0.2-301",`

**Comment by aktug** [comment]
Hello @mannol 
The documentation that you mentioned has been updated,
Please check its latest version from https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/android-smalll-icon-0000001050040134

**Comment by mannol** [comment]
Hello.

Thank you for your reply. I've tried the linked approach but still, nothing. The notification is still using the app's default launcher icon regardless of what I do.

**Comment by aktug** [comment]
Let me clarify @mannol 

1. Add this metadata to your AndroidManifest.xml
```xml
<application
...
    <meta-data
        android:name="com.huawei.messaging.default_notification_icon"
        android:resource="@drawable/ic_push_notification" />
...
</application>
```

2. Add your notification icon to res/drawable folder

![image](https://user-images.githubusercontent.com/20382405/102722353-a663de80-4311-11eb-8217-ac89c52a0729.png)

And here is an example of both custom icon and launcher icons : 
![image](https://user-images.githubusercontent.com/20382405/102722396-ef1b9780-4311-11eb-8994-df58fcec74a6.png)
![image](https://user-images.githubusercontent.com/20382405/102722425-13777400-4312-11eb-979d-e8783840014f.png)

**Comment by mannol** [comment]
@aktug yes, I did that:

Here is a tail of my `<application>` tag. Keep in mind that FCM notifications are displayed properly.

![image](https://user-images.githubusercontent.com/13100554/102722867-5fbbb780-4304-11eb-8ab0-a4683f840a88.png)

Directory structure:

![image](https://user-images.githubusercontent.com/13100554/102722878-7104c400-4304-11eb-90d9-38fa19509d97.png)

I don't have a picture of the notification popup but I can assure you, the icon is definitely not the one I expect it to be.

**Comment by aktug** [comment]
Please make sure that file is placed in "drawable" folder, not drawable-hdpi or something like that

**Comment by mannol** [comment]
I've tried using `/res/drawable/` directory as well, still nothing. Something is terribly wrong with my setup; every time I click on the notification and open up the app, `getInitialNotification()` returns empty(ish) object that doesn't contain any notifications. It doesn't matter what I do, I've tried various `click_action` values but still, nothing... Do you have any hint as to what might be going on? I'm using HTTP api to send the notifications to the client.

Thanks

**Comment by aktug** [comment]
There is no matter where do you send notification from, agc or api does not matter,
You can find example usage at [demo project](https://github.com/HMS-Core/hms-react-native-plugin/tree/master/react-native-hms-push/example)

Also, I guess conflict will be occur at initialNotification when using both firebase's push package and huawei's push package. But not sure.
