### ISSUE TITLE
iOS builds broken with react-native-hms-push

### ISSUE THREAD

**Issue by tomto1** [HMS-Core/hms-react-native-plugin#57]
Description
HmsPushMessaging causes iOS to build in runtime with

[Mon Dec 21 2020 10:34:28.716]  ERROR    TypeError: null is not an object (evaluating 'HmsPushMessaging')
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.

Environment

Platform: React-Native 0.63.3
Kit: Push
Kit Version: 5.0.2-301

**Comment by aktug** [comment]
Hello @tomto1 
**@hmscore/react-native-hms-push** currently does not support iOS,
In the next releases, we will fix these build errors and add iOS support.

Thank you for your interest 👍

**Comment by tomto1** [comment]
Ok, but how can I resolve it to build app?  I will not use it for iOS.

**Comment by aktug** [comment]
You can edit "**index.js**" of the plugin like below;

```js
if (Platform.OS === "android") { // <== Add this condition for now
  HmsPushMessaging.setBackgroundMessageHandler = (handler) => {
    if (handler && typeof handler !== "function") {
      console.error("backgroundMessageHandler must be a function.");
    }
    backgroundMessageHandler = handler;
    console.log("backgroundMessageHandler registered ✔");
  };
}
```

**Comment by tomto1** [comment]
Thx!
