### ISSUE TITLE
HmsPushEvent.onNotificationOpenedApp is getting executed even after tap in loop

### ISSUE THREAD

**Issue by arul-prasad** [HMS-Core/hms-react-native-plugin#58]
Hi all,

HmsPushEvent.onNotificationOpenedApp is got executed in the loop when we use to open the external url 

`this.huaweiPushMessageOpenedListener = HmsPushEvent.onNotificationOpenedApp((result) => {
          console.log("consolehms inside onNotificationOpenedApp ==>", result);
          if (result) {
            if (result.extras && result.extras.notification && result.extras.notification.customData) {
              let dataMessage = result.extras.notification.customData;
              Linking.openURL(dataMessage.url);
           }}`

After on tap on the message with URL, it is correctly open the URL in the browser, but when we come back to open the app, it again triggers the event onNotificationOpenedApp() and again it opens the URL in browser and it keep on loop

**Comment by ozcanozgur** [comment]
Hi,

I tried your code and realized the problem. 
onNotificationOpenedApp Listener works when return back from the url 
You can solve this problem with isUrlOpened boolean flag. Initial value will be false.

initial State
```
 this.state = {
            isUrlOpened: false,
            appState: AppState.currentState
        };
```

```
this.onNotificationOpenedAppListener = HmsPushEvent.onNotificationOpenedApp(
            (result) => {

                if (result && !this.state.isUrlOpened) {
                    if (
                        result.extras &&
                        result.extras.notification &&
                        result.extras.notification.customData
                    ) {
                        let dataMessage = result.extras.notification.customData;
                        Linking.openURL(dataMessage.url)

                        this.setState({isUrlOpened: true})
                    }
                }
            }
        );
```

Also you need to add AppState Listener.

Add to  componentDidMount()
```AppState.addEventListener('change', this._handleAppStateChange);```

Add to componentWillUnMount()
```AppState.removeEventListener('change', this._handleAppStateChange);```

Finally create AppStateChange handler
```
_handleAppStateChange = (nextAppState) => {
        if (this.state.appState.match(/inactive|background/) && nextAppState === 'active') {
            setTimeout(() => {
                this.setState({isUrlOpened: false})
            }, 500);
        }
        this.setState({appState: nextAppState});
    }
```

**Comment by arul-prasad** [comment]
Thanks a lot ozcanozgur, for your solution, we are thinking of the same solution too, we will add this, also we noticed that we are using Local notification we have to set autoCancel  = true to dismiss the notification. We are trying these solutions testing in progress, let you know the results.

**Comment by arul-prasad** [comment]
yes we tested and avoid the loop by checking with local state and we used autoCancel= true with local notification. Thanks.

but i see it as a work around we do, but it is possible fix in the plugin ?

**Comment by aktug** [comment]
yes it'll be updated with more features and improvements. thanks for interest 👍
