### ISSUE TITLE
Maps become blank after scrolling FlatList

### ISSUE THREAD

**Issue by abdelmagied94** [HMS-Core/hms-react-native-plugin#61]
The issue happens when adding a map item in a FlatList. The map renders correctly firstly but after scrolling far away, it becomes blank.

**Comment by abdelmagied94** [comment]
I think the problem is in using `TextureMapView` as the base class for `HMSMapView`. When I changed it to `MapView`, the issue disappears. There's some flicker when there's multiple maps in sequence in the list but I think because of the lite mode is not supported yet.

**Comment by utarit** [comment]
Yeah you're right. We are looking for the ways to use it with TextureMapView. If this has a work around we will notify you for the solution.

**Comment by abdelmagied94** [comment]
Please, Is there's a plan when the lite mode will be available?

**Comment by aktug** [comment]
Hello @abdelmagied94 we're working hard to implement lite mode, we'll release this feature as soon as possible, stay tuned 🎄🎄

**Comment by abdelmagied94** [comment]
@aktug Is the issue fixed with `TextureMapView`?

**Comment by aktug** [comment]
the next version will be released end of the January 2021, there will be a lot of improvements/fixes and new features, stay tuned 🎁
