### ISSUE TITLE
HMS Location issue with error code 800

### ISSUE THREAD

**Issue by ramasamy11** [HMS-Core/hms-react-native-plugin#69]
I'm trying to access the Huawei map and location in react native application for android support, After making necessary changes based on the HMS-location kit demo, I'm unable to load the maps and location.  I'm getting the below error message.

_Error while getting location settings. Error: {"errorCode":800,"errorMessage":"907135003: Connection Failed:application configuration error, please developer check configuration(10)"}_

Please let me know any changes to be done to resolve the issue. 

Platform: React-Native 0.63.4 , React 16.13.1
Kit: [Map & Location]
LocationKit:  "@hmscore/react-native-hms-location": "^5.0.0-301-02",
MapKit:"@hmscore/react-native-hms-map": "^5.0.3-302-01",
OS Version [Android 10, Android 11]
Android Studio version [ Android Studio 4.0.1]

**Comment by aktug** [comment]
Hello @ramasamy11 
Can you share any logs, it will be very useful
