### ISSUE TITLE
Please HMS ASR in Hook codes

### ISSUE THREAD

**Issue by Aung-Myint-Thein** [HMS-Core/hms-react-native-plugin#72]
I am looking at the ASR example and it looks very promising. Can we get it in hook in addition to the class codes that is available right now?

https://github.com/HMS-Core/hms-react-native-plugin/blob/master/react-native-hms-ml/example/src/HmsLanguageVoiceRelatedServices/AutomaticSpeechRecognition.js

Thanks!

**Comment by Aung-Myint-Thein** [comment]
and when I am tried `HMSAsr.createAsrRecognizer();`, i get the success message.

However, when I try to `HMSAsr.startRecognizing`, I get the "cannot invoke HMSAsr.startRecognizing null please set your app apiKey".. I followed the steps from the documentation to get the agconnect-services.json and included in the folder. However, I am using keystore file. The build is successful.

Is there anything I am missing?

**Comment by uysalemre** [comment]
Hello @Aung-Myint-Thein , 

You need to set your api key dynamically in your app.
You can find your api key in **agconnect-services.json** file.

Please use given function below before using on-cloud services in ML Kit Plugin. Please see [reference](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-References/hms-application-0000001073742333#EN-US_TOPIC_0000001073742333__section348419570588 ) for details.

```js
HMSApplication.setApiKey("<your_api_key>")
```

Before using example application please do not forget to fill the space "<your_api_key>" in setApiKey function given [here](https://github.com/HMS-Core/hms-react-native-plugin/blob/master/react-native-hms-ml/example/src/HmsOtherServices/Helper.js).

**Comment by Aung-Myint-Thein** [comment]
Hello 🙂  Thanks for the reply.

I managed to run the project after setting API key but when I try to startRecognising, get the following error messages. Any tips? Thanks!

```
{"error": 11203, "errorMessage": ",subError code: 3002,errorMessage: Service unavailable"}

{"message": "Asr recognizer is null or not created", "status": 28}
```

**Comment by uysalemre** [comment]
Hello @Aung-Myint-Thein ,

First error message means service unavailable. You need to check the network environment. 
Please see [reference](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-References/hms-asr-0000001073864089#EN-US_TOPIC_0000001073864089__section1188312862317) for error codes.

Second error message means you did not create asr recognizer. Please make sure that you get the success message from [createAsrRecognizer](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-References/hms-asr-0000001073864089#EN-US_TOPIC_0000001073864089__section9981351111010).

**Comment by Aung-Myint-Thein** [comment]
Hi @uysalemre 

The network is working and hence, I can get to the page. the speech page is 2-3 pages down from home page.

I created the asr recognizer and it returns `{"message": "Success", "status": 0}` 

I guess I am doing something wrong and could be that my code is in hook format instead of normal class format like mentioned in the example file. After chaining the whole flow in one function call, I can get the following console messages:

![Screenshot 2021-01-11 at 12 17 43 PM](https://user-images.githubusercontent.com/612366/104150100-23f9a680-5407-11eb-965f-474d1bd3ed20.png)

My code is as follow:

```
HMSApplication.setApiKey("--key--")
          .then((res) => {
            HMSAsr.createAsrRecognizer()
            .then(() => {
              HMSAsr.startRecognizing(HMSAsr.LAN_EN_US, HMSAsr.FEATURE_ALL_IN_ONE)
              .then((res) => console.log(res))
              .catch((err) => {console.log(err);})
            })
            .catch((err) => {console.log(err);})
          })
          .catch((err) => {console.log(err);})
```

However, I am still not getting the result and I think I will need a way to fire ASR_ON_RESULTS callback in hook. Am I right? Thanks for helping! Really appreciate it.

**Comment by uysalemre** [comment]
Hello @Aung-Myint-Thein ,

Your log shows the ASR_ON_VOICE_DATA_RECEIVED event.
For obtaining results you need to listen ASR_ON_RESULTS event as given in [reference](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-References/hms-asr-0000001073864089#EN-US_TOPIC_0000001073864089__section2047725313016). It will return the recognition result automatically.

**Comment by Aung-Myint-Thein** [comment]
yea.. I am already listening to ASR_ON_RESULTS but ASR_ON_ERROR returns ` {"error": 11203, "errorMessage": ",subError code: 3002,errorMessage: Service unavailable"}` ... maybe my app isn't set up properly or hasn't enabled in the Huawei App Gallery?

**Comment by uysalemre** [comment]
Hello @Aung-Myint-Thein ,

We checked and controlled Automatic Speech Recognition service. It is working properly.
