### ISSUE TITLE
app crashing on opening after integration of react-native-hms-iap

### ISSUE THREAD

**Issue by atoool** [HMS-Core/hms-react-native-plugin#8]
![WhatsApp Image 2020-09-23 at 7 57 27 PM](https://user-images.githubusercontent.com/38309272/94093670-65a41880-fe3b-11ea-9142-9bab52330f21.jpeg)

**Comment by rozeridilar** [comment]
Hello @atoool,
Demo application has 3 in-app product types: Consumables, Non-Consumables and Subscription types. You should create an application in AppGallery Connect and enable merchant services, then create the products with Demo App's requested product Ids. 
For further detail please take a look at this [video](https://www.youtube.com/watch?v=aiPFxiiUz_U&ab_channel=CodingGoals) and [documentation](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/config-product-info-0000001050766423).

**Comment by atoool** [comment]
@rozeridilar ,
i did completed integration as per the [documentation](https://github.com/HMS-Core/hms-react-native-plugin/tree/master/react-native-hms-iap) and created application in AppGallery connect, enabled merchant services ,added agconnect-services.json

**Comment by rozeridilar** [comment]
@atoool great. Lastly, to run demo app properly, you should create in-app products with the requested product ids. In the demo app, you may see product ids in **src/utils/Globals.js** file. 
Here is how your **AppGallery Connect** should be: 
![image](https://user-images.githubusercontent.com/7174879/94116798-22a26f00-fe54-11ea-97c3-617698d72f72.png)

For further details please take a look at this [video](https://www.youtube.com/watch?v=aiPFxiiUz_U&ab_channel=CodingGoals).
