### ISSUE TITLE
com.huawei.hms.rn.location.backend.logger.HMSLogger.<init>

### ISSUE THREAD

**Issue by Daha62** [HMS-Core/hms-react-native-plugin#81]
**Description**
Got an error in firebase console

```
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
```

> System:
>     OS: macOS 11.1
>     CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
>     Memory: 50.95 MB / 8.00 GB
>     Shell: 3.2.57 - /bin/bash
>   Binaries:
>     Node: 15.4.0 - /usr/local/bin/node
>     Yarn: 1.22.10 - /usr/local/bin/yarn
>     npm: 7.0.15 - /usr/local/bin/npm
>     Watchman: 4.9.0 - /usr/local/bin/watchman
>   Managers:
>     CocoaPods: 1.10.0 - /usr/local/bin/pod
>   SDKs:
>     iOS SDK:
>       Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
>     Android SDK:
>       API Levels: 19, 21, 23, 25, 26, 27, 28, 29
>       Build Tools: 26.0.2, 27.0.3, 28.0.3, 29.0.0, 29.0.2
>       System Images: android-16 | Google APIs Intel x86 Atom, android-19 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom
>       Android NDK: Not Found
>   IDEs:
>     Android Studio: 4.1 AI-201.8743.12.41.6953283
>     Xcode: 12.4/12D4e - /usr/bin/xcodebuild
>   Languages:
>     Java: 1.8.0_201 - /usr/bin/javac
>     Python: 2.7.16 - /usr/local/bin/python
>   npmPackages:
>     @react-native-community/cli: Not Found
>     react: 16.13.1 => 16.13.1 
>     react-native: 0.63.3 => 0.63.3 
>     react-native-macos: Not Found
>     @hmscore/react-native-hms-location: ^5.0.4-300

    
    
    
![image](https://user-images.githubusercontent.com/6141193/106553593-7e37e400-653b-11eb-919f-149d6704c9b1.png)

**Comment by uysalemre** [comment]
Hello @Daha62, 

Did you face this issue when you were testing your app on device ?

**Comment by Daha62** [comment]
Hello @uysalemre,
unfortunately no, I got it in production on Huawei devices (android 7 - 10).

**Comment by uysalemre** [comment]
Hello @Daha62, 

Please try to reproduce issue on your test devices, then share logs, use cases and sample code with us if issue continues.

**Comment by Daha62** [comment]
If u know there is some problems with emulators with huawei services, I dont have such devices, I have just logs from production

Here is sample code:

```
const HMSLocation = require('@hmscore/react-native-hms-location').default
      HMSLocation.LocationKit.Native.init()
        .then(() => {
          HMSLocation.FusedLocation.Native.getLastLocation()
            .then(onSuccess)
            .catch(onError)
        })
```

**Comment by uysalemre** [comment]
Hello @Daha62 ,

According to your logs, activity used in this function becomes null.
Please use [**cloud debugging functionality**](https://developer.huawei.com/consumer/en/doc/development/AppGallery-connect-Guides/agc-clouddebug-realtimedebug) to test your app, reproduce the issue and share with us, then it becomes more clear and we can find a proper solution.

**Comment by Daha62** [comment]
Unfortunately there is no such cloud devices

I got just

> Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
>        at com.huawei.hms.rn.location.backend.logger.HMSLogger.<init>(HMSLogger.java:77)
>        at com.huawei.hms.rn.location.backend.logger.HMSLogger.getInstance(HMSLogger.java:97)
>        at com.huawei.hms.rn.location.backend.providers.FusedLocationProvider.getLastLocation(FusedLocationProvider.java:156)
>        at com.huawei.hms.rn.location.RNFusedLocationModule.getLastLocation(RNFusedLocationModule.java:74)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
>        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
>        at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
>        at android.os.Handler.handleCallback(Handler.java:888)
>        at android.os.Handler.dispatchMessage(Handler.java:100)
>        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
>        at android.os.Looper.loop(Looper.java:213)
>        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
>        at java.lang.Thread.run(Thread.java:929)
