### ISSUE TITLE
docs library wrong dirPath

### ISSUE THREAD

**Issue by megaacheyounes** [HMS-Core/hms-react-native-plugin#9]
there is another library with the name react-native-hms-map, therefore to install this library one should use the command: `npm i @hmscore/react-native-hms-map`; The android src will be at: node_modules/@hmscore/react-native-hms-map/android
So in Readme.md:
`project(':react-native-hms-map').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-hms-map/android')`
should become:
`project(':react-native-hms-map').projectDir = new File(rootProject.projectDir, '../node_modules/@hmscore/react-native-hms-map/android')`

**Comment by aktug** [comment]
huh 😕 how did we miss this, thank you @megaacheyounes  🎉
